function validTagColor(v){return /^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):'#d6a85f'}
    function tagTextColor(v){const hex=validTagColor(v).slice(1),rgb=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)/255),light=rgb.map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4),lum=.2126*light[0]+.7152*light[1]+.0722*light[2];return lum>.42?'#17120b':'#fffaf2'}

function renderTagFlags(c){const tags=(c.tagIds||[]).map(id=>state.tags.find(t=>t.id===id)).filter(Boolean);return tags.length?`<div class="tag-flags">${tags.map(t=>`<span class="tag-flag" title="${escapeHtml(t.name)}" aria-label="Тег: ${escapeHtml(t.name)}" style="--tag-color:${validTagColor(t.color)}"></span>`).join('')}</div>`:''}
    function firstTagName(c){return (c.tagIds||[]).map(id=>state.tags.find(t=>t.id===id)?.name||'').filter(Boolean).sort((a,b)=>a.localeCompare(b,'ru'))[0]||'яяя'}
    function creatureMatchesQuery(c,query){const normalized=query.trim().toLocaleLowerCase('ru');return !normalized||[c.name,c.description].some(value=>String(value||'').toLocaleLowerCase('ru').includes(normalized))}
    function creatureMatchesBestiaryQuery(c,query){const normalized=query.trim().toLocaleLowerCase('ru');if(!normalized)return true;if(!bestiaryAdvancedSearch)return creatureMatchesQuery(c,query);const tagNames=(c.tagIds||[]).map(id=>state.tags.find(t=>t.id===id)?.name||'');return[c.name,c.description,c.characteristics,c.abilities,c.notes,c.inventory,...tagNames].some(value=>String(value||'').toLocaleLowerCase('ru').includes(normalized))}
    function filteredBestiary(){const list=state.bestiary.filter(c=>creatureMatchesBestiaryQuery(c,bestiaryQuery)&&[...bestiaryTagFilters].every(id=>(c.tagIds||[]).includes(id)));if(bestiarySort==='name-asc')list.sort((a,b)=>a.name.localeCompare(b.name,'ru'));if(bestiarySort==='name-desc')list.sort((a,b)=>b.name.localeCompare(a.name,'ru'));if(bestiarySort==='tag')list.sort((a,b)=>firstTagName(a).localeCompare(firstTagName(b),'ru')||a.name.localeCompare(b.name,'ru'));return list}
    function renderBestiaryCards(){const list=filteredBestiary(),cards=list.map(c=>{const i=state.bestiary.indexOf(c),flags=renderTagFlags(c);return `<article class="card bestiary-card ${flags?'has-tags':''}" data-open-detail="${c.id}" tabindex="0" role="button" aria-label="Открыть карточку существа: ${escapeHtml(c.name)}">${flags}<span class="card-kicker">Существо ${String(i+1).padStart(2,'0')}</span><h3 title="${escapeHtml(c.name)}">${escapeHtml(c.name)}</h3><p class="bestiary-description" title="${escapeHtml(c.description||'')}">${escapeHtml(c.description||'')}</p><div class="card-footer"><button class="mini compact-action" data-membership="${c.id}" aria-label="Добавить ${escapeHtml(c.name)} в комнату" title="Добавить в комнату">＋</button><button class="mini settings-icon" data-edit-creature="${c.id}" aria-label="Настройки: ${escapeHtml(c.name)}" title="Изменить существо">⚙</button><details class="card-more-menu"><summary aria-label="Дополнительные действия: ${escapeHtml(c.name)}" title="Дополнительные действия">…</summary><div class="card-more-popover"><button class="button" type="button" data-duplicate-creature="${c.id}">Дублировать</button><button class="button danger-button" type="button" data-delete-creature="${c.id}">Удалить</button></div></details></div></article>`}).join(''),addCard='<button class="bestiary-add-card" id="grid-new-creature" type="button" aria-label="Создать существо" title="Создать существо"><span aria-hidden="true">＋</span></button>';el('bestiary-grid').innerHTML=cards?cards+addCard:(state.bestiary.length?empty('Ничего не найдено','Измените название или фильтр по тегу.','',''):addCard)}

function updateBestiaryTagSummary(){const count=bestiaryTagFilters.size;el('bestiary-tag-summary').textContent=!count?'Все теги':count===1?state.tags.find(t=>bestiaryTagFilters.has(t.id))?.name||'1 тег':`${count} ${plural(count,'тег','тега','тегов')}`}
    function renderBestiaryTagOptions(){el('bestiary-tag-options').innerHTML=`<label class="tag-option"><input id="bestiary-all-tags" type="checkbox" ${bestiaryTagFilters.size?'':'checked'}><span>Все теги</span></label>${state.tags.map(t=>`<label class="tag-option"><input type="checkbox" data-bestiary-tag="${t.id}" ${bestiaryTagFilters.has(t.id)?'checked':''}><span class="tag-check-dot" style="--tag-color:${validTagColor(t.color)}"></span><span>${escapeHtml(t.name)}</span></label>`).join('')}`;updateBestiaryTagSummary()}
    function renderBestiary(){el('content').innerHTML=`<header class="page-head"><div><p class="eyebrow">Общая библиотека</p><h1>Бестиарий</h1></div><div class="actions"><details class="file-actions-menu"><summary class="button">⇅ JSON</summary><div class="file-actions-popover"><button class="button" id="download-creatures">↓ Скачать существ</button><button class="button" id="upload-creatures">↑ Загрузить существ</button><button class="button" id="import-lss-character" title="Создать существо из файла персонажа Long Story Short">↥ Импорт LSS</button></div></details><button class="button" id="manage-tags">⚑ Теги</button><button class="button primary" id="new-creature">＋ Создать существо</button></div></header><section class="bestiary-tools" aria-label="Поиск, фильтры и сортировка"><input class="tool-control" id="bestiary-search" type="search" value="${escapeHtml(bestiaryQuery)}" placeholder="${bestiaryAdvancedSearch?'Расширенный поиск по существам…':'Поиск по названию или описанию…'}" aria-label="${bestiaryAdvancedSearch?'Расширенный поиск существ':'Поиск существ по названию или описанию'}"><details class="tag-select bestiary-tag-select" id="bestiary-tag-select"><summary id="bestiary-tag-summary">Все теги</summary><div class="tag-option-list" id="bestiary-tag-options"></div></details><select class="tool-control" id="bestiary-sort" aria-label="Сортировка Бестиария"><option value="number" ${bestiarySort==='number'?'selected':''}>По номеру</option><option value="tag" ${bestiarySort==='tag'?'selected':''}>По тегу</option><option value="name-asc" ${bestiarySort==='name-asc'?'selected':''}>По алфавиту: А—Я</option><option value="name-desc" ${bestiarySort==='name-desc'?'selected':''}>По алфавиту: Я—А</option></select></section><section class="grid" id="bestiary-grid"></section>`;renderBestiaryTagOptions();renderBestiaryCards()}
