// Bestiary editor, tag management, import/export and Long Story Short import.
// This file intentionally shares the existing browser runtime scope while architecture stage 2
// gradually separates feature responsibilities without changing initialization semantics.

    function updateCreatureTagSummary(){const checked=[...el('creature-tag-checks').querySelectorAll('input:checked')];el('creature-tag-summary').textContent=!state.tags.length?'Теги не созданы':!checked.length?'Без тегов':checked.length===1?state.tags.find(t=>t.id===checked[0].value)?.name||'1 тег':`${checked.length} тегов выбрано`}
    function openCreatureDialog(id=null,roomEntryId=null,newNpc=false){editingCreatureId=id;editingRoomEntryId=roomEntryId;creatingNpcForRoom=newNpc;const room=roomById(view.roomId),entry=roomEntryById(room,roomEntryId),c=id?creatureById(id):entryCreature(entry),isNpc=newNpc||Boolean(entry&&!entry.creatureId);el('creature-dialog-kicker').textContent=isNpc?'NPC комнаты':'Существо бестиария';el('creature-dialog-title').textContent=newNpc?'Создать NPC':c?'Изменить существо':'Новое существо';el('creature-name').value=c?.name||'';el('creature-description').value=c?.description||'';el('creature-hp').value=c?.hp??'';el('creature-ac').value=c?.ac??'';el('creature-characteristics').value=c?c.characteristics||'':CHARACTERISTICS_TEMPLATE;el('creature-abilities').value=c?.abilities||'';el('creature-notes').value=c?.notes||'';el('creature-tag-checks').innerHTML=state.tags.length?state.tags.map(t=>`<label class="tag-option"><input type="checkbox" value="${t.id}" ${(c?.tagIds||[]).includes(t.id)?'checked':''}><span class="tag-check-dot" style="--tag-color:${validTagColor(t.color)}"></span><span>${escapeHtml(t.name)}</span></label>`).join(''):'<div class="tag-editor-empty">Теги ещё не созданы.</div>';el('creature-tag-select').open=false;updateCreatureTagSummary();el('creature-dialog').showModal();setTimeout(()=>el('creature-name').focus(),0)}
    function duplicateCreature(id){const source=creatureById(id);if(!source)return null;const copy={...cloneJson(source),id:makeId(),tagIds:[...(source.tagIds||[])]};state.bestiary.push(copy);save('Копия существа создана');render();openCreatureDialog(copy.id);return copy}
    function renderTagEditor(){el('tag-editor-list').innerHTML=tagDraft.length?tagDraft.map(t=>`<div class="tag-editor-row" data-tag-row="${t.id}"><input class="tag-color" type="color" value="${validTagColor(t.color)}" data-tag-color="${t.id}" aria-label="Цвет тега ${escapeHtml(t.name)}"><button class="tag-drag-handle" type="button" draggable="true" data-tag-drag="${t.id}" aria-label="Переместить тег ${escapeHtml(t.name)}" title="Перетащите тег выше или ниже">⠿</button><input class="tag-name" maxlength="30" value="${escapeHtml(t.name)}" data-tag-name="${t.id}" aria-label="Название тега" placeholder="Название тега"><button class="mini delete-icon" type="button" data-delete-tag="${t.id}" aria-label="Удалить тег">🗑</button></div>`).join(''):'<div class="tag-editor-empty">Создайте первый тег.</div>'}
    function openTagsDialog(){tagDraft=state.tags.map(t=>({...t}));renderTagEditor();el('tags-dialog').showModal()}
    function clearTagDragState(){el('tag-editor-list').querySelectorAll('.tag-editor-row').forEach(row=>row.classList.remove('dragging','drag-before','drag-after'))}
    function moveTagDraft(sourceId,targetId,after=false){const from=tagDraft.findIndex(t=>t.id===sourceId),target=tagDraft.findIndex(t=>t.id===targetId);if(from<0||target<0||sourceId===targetId)return false;const [moved]=tagDraft.splice(from,1),adjusted=tagDraft.findIndex(t=>t.id===targetId);tagDraft.splice(adjusted+(after?1:0),0,moved);return true}
    function moveTagDraftBy(sourceId,delta){const from=tagDraft.findIndex(t=>t.id===sourceId),to=Math.max(0,Math.min(tagDraft.length-1,from+delta));if(from<0||from===to)return false;const [moved]=tagDraft.splice(from,1);tagDraft.splice(to,0,moved);return true}
    function visibleExportCreatures(){return state.bestiary.filter(c=>creatureMatchesQuery(c,exportQuery))}
    function renderExportCreatures(){const list=visibleExportCreatures(),allVisible=list.length&&list.every(c=>exportSelection.has(c.id));el('export-creature-list').innerHTML=list.length?list.map(c=>`<label class="check export-row"><input type="checkbox" data-export-creature="${c.id}" ${exportSelection.has(c.id)?'checked':''}><span class="export-row-copy"><span class="export-row-name">${escapeHtml(c.name)}</span>${c.description?`<span class="export-row-description">${escapeHtml(c.description)}</span>`:''}</span></label>`).join(''):'<div class="tag-editor-empty">Ничего не найдено.</div>';el('export-select-all').textContent=allVisible?'Снять выбор':'Выбрать всех';el('export-count').textContent=`Выбрано: ${exportSelection.size}`;el('export-download').disabled=!exportSelection.size}
    function openExportDialog(){if(!state.bestiary.length){showToast('Бестиарий пока пуст');return}exportQuery='';exportSelection.clear();el('export-search').value='';renderExportCreatures();el('export-dialog').showModal();setTimeout(()=>el('export-search').focus(),0)}
    function toggleAllExportCreatures(){const list=visibleExportCreatures(),allVisible=list.length&&list.every(c=>exportSelection.has(c.id));list.forEach(c=>allVisible?exportSelection.delete(c.id):exportSelection.add(c.id));renderExportCreatures()}
    function downloadSelectedCreatures(){const creatures=state.bestiary.filter(c=>exportSelection.has(c.id)).map(c=>({...c,tagIds:[...(c.tagIds||[])]}));if(!creatures.length)return;const usedTags=new Set(creatures.flatMap(c=>c.tagIds)),payload={format:'initiative-bestiary',version:1,exportedAt:new Date().toISOString(),tags:state.tags.filter(t=>usedTags.has(t.id)).map(t=>({...t})),creatures};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`bestiary-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);el('export-dialog').close();showToast(`${creatures.length} ${plural(creatures.length,'существо скачано','существа скачаны','существ скачано')}`)}

    function prepareImportedTag(raw){if(!raw||typeof raw!=='object')return null;const sourceId=String(raw.id||''),name=String(raw.name||'').trim().slice(0,30);return name?{sourceId,name,color:validTagColor(raw.color)}:null}
    function prepareImportedCreature(raw){if(!raw||typeof raw!=='object')return null;const name=String(raw.name||'').trim().slice(0,80);if(!name)return null;const text=(value,max)=>String(value??'').slice(0,max);return{sourceId:String(raw.id||''),name,description:text(raw.description,160),hp:text(raw.hp,12),ac:text(raw.ac,6),characteristics:text(raw.characteristics,3000),abilities:text(raw.abilities,5000),notes:text(raw.notes,5000),sourceTagIds:[...new Set((Array.isArray(raw.tagIds)?raw.tagIds:[]).map(id=>String(id)).filter(Boolean))]}}
    function findImportedCreatureMatch(creature){if(creature.sourceId){const byId=state.bestiary.find(existing=>String(existing.id)===creature.sourceId);if(byId)return byId}const name=creature.name.trim().toLocaleLowerCase('ru'),sameName=state.bestiary.filter(existing=>String(existing.name||'').trim().toLocaleLowerCase('ru')===name);return sameName.length===1?sameName[0]:null}
    function renderCreatureImportPreview(){if(!pendingCreatureImport)return;const records=pendingCreatureImport.records,newCount=records.filter(record=>!record.matchId).length,conflictCount=records.length-newCount;el('import-preview-summary').innerHTML=`<div class="import-preview-stat"><strong>${newCount}</strong><span>${plural(newCount,'новое существо','новых существа','новых существ')}</span></div><div class="import-preview-stat"><strong>${conflictCount}</strong><span>${plural(conflictCount,'совпадение','совпадения','совпадений')}</span></div>`;el('import-preview-list').innerHTML=records.map(record=>{const match=record.matchId?creatureById(record.matchId):null;return `<div class="import-preview-row"><span class="import-preview-copy"><strong>${escapeHtml(record.creature.name)}</strong><span>${record.matchId?`Совпадает с «${escapeHtml(match?.name||record.creature.name)}»`:escapeHtml(record.creature.description||'Будет добавлено как новое существо')}</span></span><span class="import-preview-badge ${record.matchId?'conflict':''}">${record.matchId?'Совпадение':'Новое'}</span></div>`}).join('')}
    async function importCreaturesFile(file){if(!file)return;if(file.size>5*1024*1024){showToast('Файл слишком большой');return}try{const data=JSON.parse(await file.text()),creatures=Array.isArray(data?.creatures)?data.creatures:Array.isArray(data?.bestiary)?data.bestiary:null,tags=Array.isArray(data?.tags)?data.tags:[];if(!creatures)throw Error('invalid');const preparedTags=tags.map(prepareImportedTag).filter(Boolean),preparedCreatures=creatures.map(prepareImportedCreature).filter(Boolean);if(!preparedCreatures.length)throw Error('empty');pendingCreatureImport={fileName:file.name||'Бестиарий.json',tags:preparedTags,records:preparedCreatures.map(creature=>({creature,matchId:findImportedCreatureMatch(creature)?.id||null}))};renderCreatureImportPreview();el('import-preview-dialog').showModal()}catch(_){pendingCreatureImport=null;showToast('Не удалось прочитать файл Бестиария')}}
    function resolveCreatureImportTags(records){const needed=new Set(records.flatMap(record=>record.creature.sourceTagIds)),sourceMap=new Map();pendingCreatureImport.tags.forEach(tag=>{if(!needed.has(tag.sourceId)||!tag.sourceId)return;let existing=state.tags.find(current=>current.name.toLocaleLowerCase('ru')===tag.name.toLocaleLowerCase('ru'));if(!existing){existing={id:makeId(),name:tag.name,color:tag.color};state.tags.push(existing)}sourceMap.set(tag.sourceId,existing.id)});return sourceMap}
    function materializeImportedCreature(prepared,tagMap,id=makeId()){return{id,name:prepared.name,description:prepared.description,hp:prepared.hp,ac:prepared.ac,characteristics:prepared.characteristics,abilities:prepared.abilities,notes:prepared.notes,tagIds:prepared.sourceTagIds.map(sourceId=>tagMap.get(sourceId)).filter(Boolean)}}
    function applyCreatureImport(mode){if(!pendingCreatureImport)return;const all=pendingCreatureImport.records,selected=mode==='skip'?all.filter(record=>!record.matchId):all,tagMap=resolveCreatureImportTags(selected);let added=0,updated=0;if(mode==='update'){all.forEach(record=>{if(record.matchId){const index=state.bestiary.findIndex(c=>c.id===record.matchId);if(index>=0){state.bestiary[index]=materializeImportedCreature(record.creature,tagMap,record.matchId);updated++}}else{state.bestiary.push(materializeImportedCreature(record.creature,tagMap));added++}})}else selected.forEach(record=>{state.bestiary.push(materializeImportedCreature(record.creature,tagMap));added++});pendingCreatureImport=null;el('import-preview-dialog').close();save([added?`${added} добавлено`:'',updated?`${updated} обновлено`:''].filter(Boolean).join(' · ')||'Импорт завершён');render()}
    function lssValue(field,fallback=''){if(field==null)return fallback;if(typeof field==='object'&&Object.prototype.hasOwnProperty.call(field,'value'))return field.value??fallback;return field}
    function lssFinite(value){const number=Number(value);return Number.isFinite(number)?number:null}
    function applyLssBonuses(base,target,bonuses){let value=Number(base);if(!Number.isFinite(value))return null;(Array.isArray(bonuses)?bonuses:[]).filter(b=>b&&!b.disabled&&b.target===target).sort((a,b)=>(Number(a.priority)||0)-(Number(b.priority)||0)).forEach(b=>{const amount=lssFinite(b.value);if(amount==null)return;if(b.mode==='set'||b.kind==='override')value=amount;else if(b.mode==='multiply')value*=amount;else value+=amount});return value}
    function lssStatScore(doc,key){const raw=lssFinite(doc?.stats?.[key]?.score);if(raw==null)return 0;return applyLssBonuses(raw,`stat.${key}.score`,doc.bonuses)??raw}
    function lssStatModifier(doc,key){return Math.floor((lssStatScore(doc,key)-10)/2)}
    function evaluateLssExpression(raw,doc){const expression=String(raw??'').replace(/\[([a-z]+)\]/gi,(_,key)=>String(lssStatModifier(doc,key.toLowerCase()))).replace(/,/g,'.').replace(/\s+/g,'');if(!expression)return null;const tokens=expression.match(/\d+(?:\.\d+)?|[()+\-*/]/g);if(!tokens||tokens.join('')!==expression)return lssFinite(expression);let index=0;const factor=()=>{const token=tokens[index++];if(token==='+'||token==='-'){const value=factor();return token==='-'?-value:value}if(token==='('){const value=sum();if(tokens[index++]!==')')throw Error('paren');return value}const value=Number(token);if(!Number.isFinite(value))throw Error('number');return value},product=()=>{let value=factor();while(tokens[index]==='*'||tokens[index]==='/'){const op=tokens[index++],right=factor();value=op==='*'?value*right:value/right}return value},sum=()=>{let value=product();while(tokens[index]==='+'||tokens[index]==='-'){const op=tokens[index++],right=product();value=op==='+'?value+right:value-right}return value};try{const value=sum();return index===tokens.length&&Number.isFinite(value)?value:null}catch(_){return null}}
    function lssMaximumHp(doc){const vitality=doc?.vitality||{},base=lssFinite(lssValue(vitality['hp-max'],null));if(base==null)return '';let value=base+(lssFinite(lssValue(vitality['hp-max-bonus'],0))||0);value=applyLssBonuses(value,'hp.max',doc.bonuses)??value;return String(Math.max(0,Math.min(999999,Math.round(value))))}
    function lssArmorClass(doc){const vitality=doc?.vitality||{},raw=lssValue(vitality.ac,''),base=evaluateLssExpression(raw,doc);if(base==null)return '';let value=base;if(Boolean(lssValue(vitality.shield,false)))value+=lssFinite(vitality.shield?.mod)||0;value=applyLssBonuses(value,'ac',doc.bonuses)??value;return String(Math.max(0,Math.min(999,Math.round(value))))}
    function lssRichNode(node){if(!node)return'';if(typeof node==='string')return node;if(Array.isArray(node))return node.map(lssRichNode).join('');if(node.type==='text'){let text=String(node.text||'');const marks=Array.isArray(node.marks)?node.marks:[];if(marks.some(m=>m.type==='code'))text=`\`${text}\``;if(marks.some(m=>m.type==='italic'||m.type==='em'))text=`*${text}*`;if(marks.some(m=>m.type==='bold'||m.type==='strong'))text=`**${text}**`;return text}if(node.type==='hardBreak')return'\n';if(node.type==='resource')return node.attrs?.label||node.attrs?.name||'';const content=Array.isArray(node.content)?node.content:[];if(node.type==='heading')return`${'#'.repeat(Math.max(1,Math.min(6,Number(node.attrs?.level)||2)))} ${content.map(lssRichNode).join('')}\n`;if(node.type==='paragraph')return`${content.map(lssRichNode).join('')}\n`;if(node.type==='bulletList')return content.map(item=>`- ${lssRichNode(item).trim().replace(/\n+/g,'\n  ')}`).join('\n')+'\n';if(node.type==='orderedList')return content.map((item,i)=>`${i+1}. ${lssRichNode(item).trim().replace(/\n+/g,'\n   ')}`).join('\n')+'\n';return content.map(lssRichNode).join('')}
    function lssTextBlock(block){const value=lssValue(block,'');if(typeof value==='string')return value.trim();const data=value?.data||value;return lssRichNode(data).replace(/\n{3,}/g,'\n\n').trim()}
    function lssLabel(key){return({traits:'Черты и способности',features:'Особенности',actions:'Действия',attacks:'Атаки',equipment:'Снаряжение',personality:'Личность',ideals:'Идеалы',bonds:'Привязанности',flaws:'Слабости',notes:'Заметки',backstory:'Предыстория'}[key]||key.replace(/[-_]/g,' '))}
    function unwrapLssCharacter(raw){if(!raw||typeof raw!=='object')return null;let doc=raw;if(typeof raw.data==='string'){try{doc=JSON.parse(raw.data)}catch(_){return null}}else if(raw.data&&typeof raw.data==='object'&&(raw.data.name||raw.data.stats||raw.data.vitality))doc=raw.data;if(!doc||typeof doc!=='object'||(!doc.name&&!doc.stats&&!doc.vitality))return null;return doc}
    function lssCreatureFromDocument(doc){const name=String(lssValue(doc.name,'')).trim().slice(0,80);if(!name)throw Error('name');const info=doc.info||{},race=String(lssValue(info.race,'')).trim(),charClass=String(lssValue(info.charClass,'')).trim(),subclass=String(lssValue(info.charSubclass,'')).trim(),level=lssValue(info.level,''),classLine=[charClass,level!==''&&level!=null?`${level} ур.`:''].filter(Boolean).join(' '),description=[race,classLine,subclass].filter(Boolean).join(' — ').slice(0,160);const statKeys=[['str','С'],['dex','Л'],['con','Т'],['int','И'],['wis','М'],['cha','X']],characteristics=statKeys.map(([key,label])=>`${label}:${lssStatModifier(doc,key)}`).join(' | ');const textEntries=Object.entries(doc.text||{}).map(([key,block])=>({key,text:lssTextBlock(block)})).filter(item=>item.text),abilityKeys=/trait|feature|abilit|action|attack|spell/i,abilityParts=textEntries.filter(item=>abilityKeys.test(item.key)).map(item=>`## ${lssLabel(item.key)}\n${item.text}`),noteParts=textEntries.filter(item=>!abilityKeys.test(item.key)).map(item=>`## ${lssLabel(item.key)}\n${item.text}`);const weapons=(Array.isArray(doc.weaponsList)?doc.weaponsList:[]).map(w=>{const weaponName=String(lssValue(w?.name,'Оружие')).trim()||'Оружие',damage=String(lssValue(w?.dmg,'')).trim(),type=String(lssValue(w?.dmgType,'')).trim(),extra=String(lssValue(w?.notes,'')).trim(),tail=[damage&&`урон ${damage}`,type,extra].filter(Boolean).join(', ');return`**${weaponName}.**${tail?` ${tail}`:''}`});if(weapons.length)abilityParts.push(`## Оружие\n${weapons.join('\n')}`);const resources=Object.values(doc.resources||{}).filter(Boolean).map(resource=>`**${String(resource.name||'Ресурс')}.** ${resource.current??'—'}/${resource.max??'—'}`);if(resources.length)abilityParts.push(`## Ресурсы\n${resources.join('\n')}`);const details=[["Игрок",lssValue(info.playerName,'')],["Предыстория",lssValue(info.background,'')],["Мировоззрение",lssValue(info.alignment,'')],["Скорость",lssValue(doc.vitality?.speed,'')]].filter(([,value])=>value!==''&&value!=null).map(([label,value])=>`**${label}:** ${value}`);const maxHp=lssMaximumHp(doc),currentHp=lssValue(doc.vitality?.['hp-current'],'');if(currentHp!==''&&String(currentHp)!==maxHp)details.push(`**Текущие ХП при импорте:** ${currentHp}`);if(details.length)noteParts.unshift(`## Сведения из LSS\n${details.join('\n')}`);return{name,description,hp:maxHp,ac:lssArmorClass(doc),characteristics,abilities:abilityParts.join('\n\n').slice(0,5000),notes:noteParts.join('\n\n').slice(0,5000),tagIds:[]}}
    async function importLssCharacterFile(file){if(!file)return;if(file.size>5*1024*1024){showToast('Файл слишком большой');return}try{const raw=JSON.parse(await file.text()),doc=unwrapLssCharacter(raw);if(!doc)throw Error('format');const creature=lssCreatureFromDocument(doc);openCreatureDialog();el('creature-dialog-kicker').textContent='Импорт Long Story Short';el('creature-dialog-title').textContent='Проверить персонажа';el('creature-name').value=creature.name;el('creature-description').value=creature.description;el('creature-hp').value=creature.hp;el('creature-ac').value=creature.ac;el('creature-characteristics').value=creature.characteristics;el('creature-abilities').value=creature.abilities;el('creature-notes').value=creature.notes;showToast('Персонаж LSS распознан — проверьте данные')}catch(_){showToast('Не удалось распознать персонажа Long Story Short')}}
