    let battleNoteMenuTarget=null,battleNoteMenuSelection=null,battleNoteLongPressTimer=null,battleNoteLongPressStart=null;
    function closeBattleNoteMenu(){const menu=el('battle-note-menu');if(menu)menu.hidden=true;battleNoteMenuTarget=null;battleNoteMenuSelection=null}
    function openBattleNoteMenu(area,x,y){if(!area)return;const menu=el('battle-note-menu');battleNoteMenuTarget=area;battleNoteMenuSelection={start:area.selectionStart,end:area.selectionEnd};menu.hidden=false;menu.style.left='0px';menu.style.top='0px';const rect=menu.getBoundingClientRect(),left=Math.max(8,Math.min(window.innerWidth-rect.width-8,x)),top=Math.max(8,Math.min(window.innerHeight-rect.height-8,y));menu.style.left=left+'px';menu.style.top=top+'px'}
    function applyBattleNoteFormat(type){const area=battleNoteMenuTarget,selection=battleNoteMenuSelection;if(!area||!selection)return;area.focus();area.setSelectionRange(selection.start,selection.end);const formats={bold:['**','**','жирный текст'],italic:['*','*','курсив'],strike:['~~','~~','зачёркнутый текст']};if(formats[type])wrapMarkdown(area,...formats[type]);else if(type==='task')toggleMarkdownTask(area);else if(type==='resource')insertMarkdownResource(area);closeBattleNoteMenu();endBattleNoteEditing(area)}

    function registerBonusHpEvents(){
    document.addEventListener('input',e=>{const input=e.target.closest('[data-bonus-hp]');if(!input)return;const room=roomById(view.roomId);if(!room)return;room.bonusHp=room.bonusHp&&typeof room.bonusHp==='object'?room.bonusHp:{};const raw=input.value.trim(),number=Number(raw);if(raw===''||!Number.isFinite(number))room.bonusHp[input.dataset.bonusHp]='';else{const clean=Math.max(0,Math.min(999999,Math.trunc(number)));input.value=String(clean);room.bonusHp[input.dataset.bonusHp]=String(clean)}save()})
    }

    function registerBattleNotePreviewEvents(){
    document.addEventListener('click',e=>{const task=e.target.closest('[data-battle-task]');if(task){e.stopPropagation();const room=roomById(view.roomId);if(!room)return;const key=task.dataset.battleTask,lines=String(room.combatNotes[key]||'').split(/\r?\n/),index=Number(task.dataset.battleLine),line=String(lines[index]||''),match=line.match(/^(\s*[-*]\s+)\[([ xX])\](\s*)(.*)$/);if(!match)return;lines[index]=match[1]+(task.checked?'[x]':'[ ]')+match[3]+match[4];room.combatNotes[key]=lines.join('\n');const area=document.querySelector(`[data-combat-note="${CSS.escape(String(key))}"]`);if(area)area.value=room.combatNotes[key];save();const preview=document.querySelector(`[data-combat-note-preview="${CSS.escape(String(key))}"]`);if(preview){preview.innerHTML=renderBattleNotePreview(room.combatNotes[key],key);preview.classList.toggle('is-empty',!room.combatNotes[key].trim())}return}const resource=e.target.closest('[data-battle-resource]');if(resource){e.stopPropagation();const room=roomById(view.roomId);if(!room)return;const key=resource.dataset.battleResource,lines=String(room.combatNotes[key]||'').split(/\r?\n/),index=Number(resource.dataset.battleLine),start=Number(resource.dataset.battleResourceStart),line=String(lines[index]||''),token=line.slice(start,start+3);if(!/^\[[ xX]\]$/.test(token))return;lines[index]=line.slice(0,start)+(/^\[[xX]\]$/.test(token)?'[ ]':'[x]')+line.slice(start+3);room.combatNotes[key]=lines.join('\n');const area=document.querySelector(`[data-combat-note="${CSS.escape(String(key))}"]`);if(area)area.value=room.combatNotes[key];save();const preview=document.querySelector(`[data-combat-note-preview="${CSS.escape(String(key))}"]`);if(preview){preview.innerHTML=renderBattleNotePreview(room.combatNotes[key],key);preview.classList.toggle('is-empty',!room.combatNotes[key].trim())}return}const preview=e.target.closest('[data-combat-note-preview]');if(preview)beginBattleNoteEditing(preview.dataset.combatNotePreview)})
    document.addEventListener('keydown',e=>{const preview=e.target.closest?.('[data-combat-note-preview]');if(preview&&(e.key==='Enter'||e.key===' ')){e.preventDefault();beginBattleNoteEditing(preview.dataset.combatNotePreview)}})
    document.addEventListener('focusout',e=>{const area=e.target.closest?.('[data-combat-note]');if(!area)return;requestAnimationFrame(()=>{const menu=el('battle-note-menu');if(battleNoteMenuTarget===area&&menu&&!menu.hidden)return;if(document.activeElement?.closest?.('#battle-note-menu'))return;endBattleNoteEditing(area)})})
    }

    function registerBattleNoteMenuEvents(){
    document.addEventListener('contextmenu',e=>{const direct=e.target.closest?.('[data-combat-note]'),preview=e.target.closest?.('[data-combat-note-preview]'),area=direct||preview&&beginBattleNoteEditing(preview.dataset.combatNotePreview,false);if(!area)return;e.preventDefault();openBattleNoteMenu(area,e.clientX,e.clientY)})
    document.addEventListener('pointerdown',e=>{const direct=e.target.closest?.('[data-combat-note]'),preview=e.target.closest?.('[data-combat-note-preview]');if((!direct&&!preview)||!['touch','pen'].includes(e.pointerType))return;clearTimeout(battleNoteLongPressTimer);battleNoteLongPressStart={x:e.clientX,y:e.clientY};battleNoteLongPressTimer=setTimeout(()=>{const area=direct||preview&&beginBattleNoteEditing(preview.dataset.combatNotePreview,false);if(area)openBattleNoteMenu(area,e.clientX,e.clientY)},560)})
    document.addEventListener('pointermove',e=>{if(!battleNoteLongPressTimer||!battleNoteLongPressStart)return;if(Math.hypot(e.clientX-battleNoteLongPressStart.x,e.clientY-battleNoteLongPressStart.y)>12){clearTimeout(battleNoteLongPressTimer);battleNoteLongPressTimer=null}})
    ;['pointerup','pointercancel'].forEach(type=>document.addEventListener(type,()=>{clearTimeout(battleNoteLongPressTimer);battleNoteLongPressTimer=null;battleNoteLongPressStart=null}))
    document.addEventListener('pointerdown',e=>{const menu=el('battle-note-menu');if(menu&&!menu.hidden&&!e.target.closest('#battle-note-menu')&&!e.target.closest('[data-combat-note]')&&!e.target.closest('[data-combat-note-preview]'))closeBattleNoteMenu()})
    document.addEventListener('click',e=>{const action=e.target.closest('[data-battle-note-format]');if(!action)return;e.preventDefault();applyBattleNoteFormat(action.dataset.battleNoteFormat)})
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!el('battle-note-menu')?.hidden)closeBattleNoteMenu()})
    }

    function registerOutsideCombatToggleEvents(){
    document.addEventListener('click',e=>{if(!e.target.closest('#toggle-outside-combat'))return;const room=roomById(view.roomId);if(!room)return;room.outsideCombatCollapsed=!room.outsideCombatCollapsed;save();render()})
    }

    function registerCombatUndoEvents(){
    document.addEventListener('keydown',e=>{if(!e.ctrlKey||e.altKey||e.metaKey||e.shiftKey)return;const key=String(e.key||'').toLocaleLowerCase('ru'),isUndo=e.code==='KeyZ'||key==='z'||key==='я';if(!isUndo)return;const target=e.target;if(target?.closest?.('input,textarea,select,[contenteditable="true"]'))return;const room=roomById(view.roomId);if(view.name!=='room'||!room?.combat?.active||!canUndoCombat(room))return;e.preventDefault();undoCombatAction()})
    }

    function registerCombatConditionEvents(){
    document.addEventListener('click',e=>{const manage=e.target.closest('[data-manage-combat-conditions]');if(manage){openCombatConditionDialog(manage.dataset.manageCombatConditions);return}const open=e.target.closest('[data-open-combat-condition]');if(open){openLibraryItemDetail('conditions',open.dataset.openCombatCondition);return}const remove=e.target.closest('[data-remove-combat-condition]');if(remove){removeCombatCondition(remove.dataset.conditionEntry,remove.dataset.removeCombatCondition);return}})
    document.addEventListener('input',e=>{const search=e.target.closest('#combat-condition-search');if(!search)return;combatConditionSearch=search.value;renderCombatConditionOptions()})
    const form=el('combat-condition-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const changed=saveCombatConditionSelection();el('combat-condition-dialog').close();combatConditionEntryId=null;combatConditionSearch='';if(changed)render()})
    const dialog=el('combat-condition-dialog');if(dialog)dialog.addEventListener('close',()=>{combatConditionEntryId=null;combatConditionSearch=''})
    }
