    function fullBackupSettings(){return{...cloudSettings(),tokenCustomColor:tokenatorCustomColor}}
    function fullBackupFileName(date=new Date()){return `WreckTrack-Data-v${CURRENT_SCHEMA_VERSION}-${date.toISOString().slice(0,10)}.json`}
    function fullBackupStats(archive){const rooms=Array.isArray(archive?.rooms)?archive.rooms:[],bestiary=Array.isArray(archive?.bestiary)?archive.bestiary:[],tags=Array.isArray(archive?.tags)?archive.tags:[],npcs=rooms.reduce((sum,room)=>sum+(Array.isArray(room.entries)?room.entries.filter(entry=>!entry?.creatureId).length:0),0);return{rooms:rooms.length,bestiary:bestiary.length,tags:tags.length,npcs}}
    function createFullBackup(){const exportedAt=new Date(),payload={format:'wrecktrack-data',formatVersion:1,schemaVersion:CURRENT_SCHEMA_VERSION,exportedAt:exportedAt.toISOString(),archive:cloneJson(state),settings:fullBackupSettings()},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a'),fileName=fullBackupFileName(exportedAt);link.href=url;link.download=fileName;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`Создана резервная копия: ${fileName}`)}
    function parseFullBackupPayload(data){if(!plainObject(data)||data.format!=='wrecktrack-data'||Number(data.formatVersion)!==1)throw new Error('format');if(!plainObject(data.archive)||!Array.isArray(data.archive.rooms)||!Array.isArray(data.archive.bestiary))throw new Error('archive');const declaredVersion=Number(data.schemaVersion??data.archive.schemaVersion??0);if(!Number.isInteger(declaredVersion)||declaredVersion<0)throw new Error('schema');if(declaredVersion>CURRENT_SCHEMA_VERSION)throw new Error('future');const rawArchive=cloneJson(data.archive),archiveVersion=archiveSchemaVersion(rawArchive);if(archiveVersion&&declaredVersion&&archiveVersion!==declaredVersion)throw new Error('schema-mismatch');if(!archiveVersion)rawArchive.schemaVersion=declaredVersion;const archive=normalize(rawArchive),settings=plainObject(data.settings)?cloneJson(data.settings):{},exportedAt=typeof data.exportedAt==='string'?data.exportedAt:'';return{archive,settings,exportedAt,schemaVersion:archive.schemaVersion}}
    function renderFullBackupPreview(parsed,fileName){const stats=fullBackupStats(parsed.archive),rawDate=Date.parse(parsed.exportedAt),dateText=Number.isFinite(rawDate)?new Date(rawDate).toLocaleString('ru-RU'):'Дата не указана';el('backup-restore-summary').innerHTML=`<div class="backup-summary-head"><strong>${escapeHtml(fileName)}</strong><span>Схема v${parsed.schemaVersion} · ${escapeHtml(dateText)}</span></div><div class="backup-summary-grid"><div class="backup-summary-item"><strong>${stats.bestiary}</strong><span>${plural(stats.bestiary,'существо','существа','существ')}</span></div><div class="backup-summary-item"><strong>${stats.rooms}</strong><span>${plural(stats.rooms,'комната','комнаты','комнат')}</span></div><div class="backup-summary-item"><strong>${stats.tags}</strong><span>${plural(stats.tags,'тег','тега','тегов')}</span></div><div class="backup-summary-item"><strong>${stats.npcs}</strong><span>NPC в комнатах</span></div></div>`}
    let pendingFullBackupRestore=null;
    async function openFullBackupRestore(file){if(!file)return;if(file.size>20*1024*1024){showToast('Резервная копия должна быть не больше 20 МБ');return}try{const parsed=parseFullBackupPayload(JSON.parse(await file.text()));pendingFullBackupRestore={...parsed,fileName:file.name||'WreckTrack-Data.json'};renderFullBackupPreview(parsed,pendingFullBackupRestore.fileName);el('backup-restore-dialog').showModal()}catch(error){const message=error?.message==='future'?'Эта резервная копия создана в более новой версии WreckTrack':error?.message==='schema-mismatch'?'Версии данных в резервной копии не совпадают':'Не удалось прочитать резервную копию WreckTrack';showToast(message)}}
    function applyFullBackupSettings(settings){applyCloudSettings(settings);const custom=normalizeTokenColor(settings?.tokenCustomColor);if(custom)tokenatorCustomColor=custom;persistTokenColors()}
    function restoreFullBackup(mode){const pending=pendingFullBackupRestore;if(!pending)return;if(mode==='replace'){state=normalize(cloneJson(pending.archive));applyFullBackupSettings(pending.settings)}else{const base=normalize({rooms:[],bestiary:[],tags:[]}),merged=mergeConcurrentData(base,state,pending.archive,{},fullBackupSettings(),pending.settings);state=merged.state;applyFullBackupSettings(merged.settings)}markLocalMutation();persistLocalState();scheduleCloudSave();pendingFullBackupRestore=null;el('backup-restore-dialog').close();render();showToast(mode==='replace'?'Данные восстановлены из резервной копии':'Резервная копия объединена с текущими данными')}
