const librarySearch={conditions:'',artifacts:''};
const librarySort={conditions:'number',artifacts:'number'};
const libraryTagFilters={conditions:new Set(),artifacts:new Set()};
let editingLibraryType=null,editingLibraryItemId=null,artifactAssignmentItemId=null,artifactAssignmentQuery='',artifactAssignmentSelection=new Set();

function libraryMeta(type){
  return type==='artifacts'
    ?{singular:'Артефакт',plural:'Артефакты',newTitle:'Новый артефакт',changed:'Артефакт изменён',created:'Артефакт создан',deleted:'Артефакт удалён',eyebrow:'Предметы и реликвии',empty:'Артефактов пока нет',description:'Предметы, реликвии и другие игровые материалы.'}
    :{singular:'Состояние',plural:'Состояния',newTitle:'Новое состояние',changed:'Состояние изменено',created:'Состояние создано',deleted:'Состояние удалено',eyebrow:'Правила и эффекты',empty:'Состояний пока нет',description:'Стандартные состояния D&D и ваши собственные эффекты.'}
}
function libraryItems(type){return type==='artifacts'?state.library.artifacts:state.library.conditions}
function libraryItemById(type,id){return libraryItems(type).find(item=>item.id===id)}
function artifactAssignmentTargets(){const targets=state.bestiary.map(creature=>({key:`bestiary:${creature.id}`,creature,context:'Бестиарий',creatureId:creature.id}));state.rooms.forEach(room=>room.entries.forEach(entry=>{if(entry.npc)targets.push({key:`npc:${room.id}:${entry.id}`,creature:entry.npc,context:room.name,roomId:room.id,entryId:entry.id})}));return targets}
function deleteArtifactRoomState(room,entryId,artifactId){const entryStates=room?.artifactStates?.[entryId];if(!entryStates)return;delete entryStates[artifactId];if(!Object.keys(entryStates).length)delete room.artifactStates[entryId]}
function clearArtifactAssignmentState(target,artifactId){if(target.creatureId){state.rooms.forEach(room=>room.entries.filter(entry=>entry.creatureId===target.creatureId).forEach(entry=>deleteArtifactRoomState(room,entry.id,artifactId)));return}const room=roomById(target.roomId);if(room&&target.entryId)deleteArtifactRoomState(room,target.entryId,artifactId)}
function renderArtifactAssignmentOptions(){const box=el('artifact-assignment-checks');if(!box)return;const query=artifactAssignmentQuery.trim().toLocaleLowerCase('ru'),targets=artifactAssignmentTargets().filter(target=>!query||[target.creature.name,target.creature.description,target.context].some(value=>String(value||'').toLocaleLowerCase('ru').includes(query)));box.innerHTML=targets.length?targets.map(target=>`<label class="check artifact-assignment-row"><input type="checkbox" value="${escapeHtml(target.key)}" ${artifactAssignmentSelection.has(target.key)?'checked':''}><span class="artifact-assignment-copy"><strong>${escapeHtml(target.creature.name||'Без имени')}</strong><small>${escapeHtml(target.context)}</small></span></label>`).join(''):`<div class="tag-editor-empty">${artifactAssignmentTargets().length?'Ничего не найдено.':'Сначала создайте хотя бы одно существо.'}</div>`}
function openArtifactAssignment(id){const artifact=libraryItemById('artifacts',id);if(!artifact)return;artifactAssignmentItemId=id;artifactAssignmentQuery='';artifactAssignmentSelection=new Set(artifactAssignmentTargets().filter(target=>(target.creature.artifactIds||[]).includes(id)).map(target=>target.key));el('artifact-assignment-title').textContent=`Существа: ${artifact.name}`;el('artifact-assignment-search').value='';renderArtifactAssignmentOptions();el('artifact-assignment-dialog').showModal();setTimeout(()=>el('artifact-assignment-search').focus(),0)}
function saveArtifactAssignments(){const artifact=libraryItemById('artifacts',artifactAssignmentItemId);if(!artifact)return false;let changed=false;artifactAssignmentTargets().forEach(target=>{const before=[...new Set(Array.isArray(target.creature.artifactIds)?target.creature.artifactIds:[])],has=before.includes(artifact.id),want=artifactAssignmentSelection.has(target.key);if(has===want)return;target.creature.artifactIds=want?[...before,artifact.id]:before.filter(id=>id!==artifact.id);if(!want)clearArtifactAssignmentState(target,artifact.id);changed=true});if(changed)save('Артефакт назначен существам');return changed}
function currentLibraryTags(){return state.library.syncTags?state.tags:state.library.tags}
function renderLibraryTagFlags(item){const tags=(item.tagIds||[]).map(id=>currentLibraryTags().find(tag=>tag.id===id)).filter(Boolean);return tags.length?`<div class="tag-flags">${tags.map(tag=>`<span class="tag-flag" title="${escapeHtml(tag.name)}" aria-label="Тег: ${escapeHtml(tag.name)}" style="--tag-color:${validTagColor(tag.color)}"></span>`).join('')}</div>`:''}
function firstLibraryTagName(item){return (item.tagIds||[]).map(id=>currentLibraryTags().find(tag=>tag.id===id)?.name||'').filter(Boolean).sort((a,b)=>a.localeCompare(b,'ru'))[0]||'яяя'}
function libraryItemMatches(item,type){const query=librarySearch[type].trim().toLocaleLowerCase('ru'),tags=currentLibraryTags(),tagNames=(item.tagIds||[]).map(id=>tags.find(tag=>tag.id===id)?.name||'');return(!query||[item.name,item.description,item.details,...tagNames].some(value=>String(value||'').toLocaleLowerCase('ru').includes(query)))&&[...libraryTagFilters[type]].every(id=>(item.tagIds||[]).includes(id))}
function filteredLibraryItems(type){const list=libraryItems(type).filter(item=>libraryItemMatches(item,type));if(librarySort[type]==='name-asc')list.sort((a,b)=>a.name.localeCompare(b.name,'ru'));if(librarySort[type]==='name-desc')list.sort((a,b)=>b.name.localeCompare(a.name,'ru'));if(librarySort[type]==='tag')list.sort((a,b)=>firstLibraryTagName(a).localeCompare(firstLibraryTagName(b),'ru')||a.name.localeCompare(b.name,'ru'));return list}
function updateLibraryTagSummary(type){const summary=el('library-tag-summary'),filters=libraryTagFilters[type],tags=currentLibraryTags();if(!summary)return;summary.textContent=!filters.size?'Все теги':filters.size===1?tags.find(tag=>filters.has(tag.id))?.name||'1 тег':`${filters.size} ${plural(filters.size,'тег','тега','тегов')}`}
function renderLibraryTagOptions(type){const box=el('library-tag-options'),filters=libraryTagFilters[type],tags=currentLibraryTags();if(!box)return;box.innerHTML=`<label class="tag-option"><input id="library-all-tags" type="checkbox" ${filters.size?'':'checked'}><span>Все теги</span></label>${tags.map(tag=>`<label class="tag-option"><input type="checkbox" data-library-tag="${tag.id}" ${filters.has(tag.id)?'checked':''}><span class="tag-check-dot" style="--tag-color:${validTagColor(tag.color)}"></span><span>${escapeHtml(tag.name)}</span></label>`).join('')}`;updateLibraryTagSummary(type)}
function renderLibraryCards(type){const grid=el('library-grid');if(!grid)return;const meta=libraryMeta(type),all=libraryItems(type),list=filteredLibraryItems(type),cards=list.map(item=>{const index=all.indexOf(item),flags=renderLibraryTagFlags(item),assign=type==='artifacts'?`<button class="mini compact-action" type="button" data-assign-artifact="${item.id}" aria-label="Добавить ${escapeHtml(item.name)} существу" title="Добавить существу">＋</button>`:'';return `<article class="card bestiary-card library-card ${flags?'has-tags':''}" data-open-library-item="${item.id}" tabindex="0" role="button" aria-label="Открыть: ${escapeHtml(item.name)}">${flags}<span class="card-kicker">${meta.singular} ${String(index+1).padStart(2,'0')}</span><h3 title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</h3><p class="bestiary-description" title="${escapeHtml(item.description||'')}">${escapeHtml(item.description||'')}</p><div class="card-footer">${assign}<button class="mini settings-icon" type="button" data-edit-library-item="${item.id}" aria-label="Изменить: ${escapeHtml(item.name)}" title="Изменить">⚙</button><details class="card-more-menu"><summary aria-label="Дополнительные действия: ${escapeHtml(item.name)}" title="Дополнительные действия">…</summary><div class="card-more-popover"><button class="button" type="button" data-duplicate-library-item="${item.id}">Дублировать</button><button class="button danger-button" type="button" data-delete-library-item="${item.id}">Удалить</button></div></details></div></article>`}).join(''),addCard=`<button class="bestiary-add-card" id="grid-new-library-item" type="button" aria-label="Создать ${meta.singular.toLocaleLowerCase('ru')}" title="Создать ${meta.singular.toLocaleLowerCase('ru')}"><span aria-hidden="true">＋</span></button>`;grid.innerHTML=cards?cards+addCard:(all.length?empty('Ничего не найдено','Измените поиск или фильтр по тегам.','',''):addCard)}
function renderLibrary(){el('content').innerHTML=`<header class="page-head"><div><p class="eyebrow">Материалы мастера</p><h1>Библиотека</h1><p class="lead">Справочные материалы для игры, которые можно дополнять и настраивать под кампанию.</p></div></header><section class="library-home-grid"><button class="portal library-portal" data-go="library-conditions"><span class="portal-index">РАЗДЕЛ 01</span><span class="portal-arrow">→</span><h2>Состояния</h2><p>${state.library.conditions.length} ${plural(state.library.conditions.length,'состояние','состояния','состояний')}</p></button><button class="portal library-portal" data-go="library-artifacts"><span class="portal-index">РАЗДЕЛ 02</span><span class="portal-arrow">→</span><h2>Артефакты</h2><p>${state.library.artifacts.length} ${plural(state.library.artifacts.length,'артефакт','артефакта','артефактов')}</p></button></section>`}
function renderLibrarySection(type){const meta=libraryMeta(type),presetMenu=type==='conditions'?`<details class="library-preset-menu"><summary class="button">Предустановить</summary><div class="library-preset-popover"><button class="button" type="button" data-condition-preset="5e14">Предустановить состояния 5е14</button><button class="button" type="button" data-condition-preset="5e24">Предустановить состояния 5е24</button><button class="button" type="button" data-condition-preset="both">Предустановить 5е14 и 5е24</button></div></details>`:'';el('content').innerHTML=`<header class="page-head"><div><p class="eyebrow">${meta.eyebrow}</p><h1>${meta.plural}</h1><p class="lead">${meta.description}</p></div><div class="actions"><button class="button" type="button" data-go="library">← Библиотека</button>${presetMenu}<button class="button" id="manage-library-tags" type="button">⚑ Теги</button><button class="button primary" id="new-library-item" type="button">＋ Создать ${meta.singular.toLocaleLowerCase('ru')}</button></div></header><section class="bestiary-tools library-tools" aria-label="Поиск, фильтры и сортировка"><input class="tool-control" id="library-search" type="search" value="${escapeHtml(librarySearch[type])}" placeholder="Поиск по названию, описанию или тегам…" aria-label="Поиск: ${meta.plural}"><details class="tag-select bestiary-tag-select" id="library-tag-select"><summary id="library-tag-summary">Все теги</summary><div class="tag-option-list" id="library-tag-options"></div></details><select class="tool-control" id="library-sort" aria-label="Сортировка"><option value="number" ${librarySort[type]==='number'?'selected':''}>По номеру</option><option value="tag" ${librarySort[type]==='tag'?'selected':''}>По тегу</option><option value="name-asc" ${librarySort[type]==='name-asc'?'selected':''}>По алфавиту: А—Я</option><option value="name-desc" ${librarySort[type]==='name-desc'?'selected':''}>По алфавиту: Я—А</option></select></section><section class="grid" id="library-grid"></section>`;renderLibraryTagOptions(type);renderLibraryCards(type)}
function libraryTypeFromView(){return view.name==='library-artifacts'?'artifacts':view.name==='library-conditions'?'conditions':null}
function updateLibraryItemTagSummary(){const box=el('library-item-tag-checks'),summary=el('library-item-tag-summary'),tags=currentLibraryTags();if(!box||!summary)return;const checked=[...box.querySelectorAll('input:checked')];summary.textContent=!tags.length?'Теги не созданы':!checked.length?'Без тегов':checked.length===1?tags.find(tag=>tag.id===checked[0].value)?.name||'1 тег':`${checked.length} тегов выбрано`}
function openLibraryItemDetail(type,id){const meta=libraryMeta(type),item=libraryItemById(type,id);if(!item)return;const tags=(item.tagIds||[]).map(tagId=>currentLibraryTags().find(tag=>tag.id===tagId)).filter(Boolean);el('library-detail-content').innerHTML=`<div class="library-detail-head"><div><p class="eyebrow">${meta.singular}</p><h3>${escapeHtml(item.name)}</h3><p class="library-detail-description">${escapeHtml(item.description||'')}</p></div><button class="auth-close" type="button" data-close="library-detail-dialog" aria-label="Закрыть">✕</button></div>${tags.length?`<div class="library-detail-tags">${tags.map(tag=>`<span class="library-detail-tag" style="--tag-color:${validTagColor(tag.color)}"><span class="tag-check-dot"></span>${escapeHtml(tag.name)}</span>`).join('')}</div>`:''}<div class="markdown library-detail-body">${renderMarkdown(item.details||item.description||'Не указано')}</div><div class="dialog-actions"><button class="button" type="button" data-close="library-detail-dialog">Закрыть</button><button class="button primary" type="button" data-edit-library-detail="${item.id}" data-library-detail-type="${type}">Изменить</button></div>`;el('library-detail-dialog').showModal()}
function openLibraryItemDialog(type,id=null){const meta=libraryMeta(type),item=id?libraryItemById(type,id):null;editingLibraryType=type;editingLibraryItemId=id;el('library-item-kicker').textContent=meta.singular;el('library-item-title').textContent=item?`Изменить: ${item.name}`:meta.newTitle;el('library-item-name').value=item?.name||'';el('library-item-description').value=item?.description||'';el('library-item-details').value=item?.details||'';const tags=currentLibraryTags();el('library-item-tag-checks').innerHTML=tags.length?tags.map(tag=>`<label class="tag-option"><input type="checkbox" value="${tag.id}" ${(item?.tagIds||[]).includes(tag.id)?'checked':''}><span class="tag-check-dot" style="--tag-color:${validTagColor(tag.color)}"></span><span>${escapeHtml(tag.name)}</span></label>`).join(''):'<div class="tag-editor-empty">Теги ещё не созданы.</div>';el('library-item-tag-select').open=false;updateLibraryItemTagSummary();el('library-item-dialog').showModal();setTimeout(()=>el('library-item-name').focus(),0)}
function duplicateLibraryItem(type,id){const source=libraryItemById(type,id);if(!source)return;const copy={...cloneJson(source),id:makeId(),builtin:false,tagIds:[...(source.tagIds||[])]};libraryItems(type).push(copy);save(`${libraryMeta(type).singular}: копия создана`);render();openLibraryItemDialog(type,copy.id)}
function deleteLibraryItem(type,id){const item=libraryItemById(type,id);if(!item||!confirm(`Удалить «${item.name}» из Библиотеки?`))return;state.library[type]=libraryItems(type).filter(entry=>entry.id!==id);if(type==='conditions')state.rooms.forEach(room=>{if(!room.conditions||typeof room.conditions!=='object')return;for(const [entryId,ids] of Object.entries(room.conditions)){const next=(Array.isArray(ids)?ids:[]).filter(conditionId=>conditionId!==id);if(next.length)room.conditions[entryId]=next;else delete room.conditions[entryId]}});if(type==='artifacts'){state.bestiary.forEach(creature=>creature.artifactIds=(creature.artifactIds||[]).filter(artifactId=>artifactId!==id));state.rooms.forEach(room=>{room.entries.forEach(entry=>{if(entry.npc)entry.npc.artifactIds=(entry.npc.artifactIds||[]).filter(artifactId=>artifactId!==id)});Object.keys(room.artifactStates||{}).forEach(entryId=>deleteArtifactRoomState(room,entryId,id))})}save(libraryMeta(type).deleted);render()}
function conditionPresetMatchKey(item){const baseId=String(item?.id||'').replace(/-(5e14|5e24)$/,'');return `${item?.preset||''}:${baseId}`}
function installConditionPreset(presetId){const preset=DND_CONDITION_PRESETS[presetId];if(!preset)return;const label=presetId==='5e14'?'D&D 5е14':presetId==='5e24'?'D&D 5е24':'D&D 5е14 и 5е24',builtins=state.library.conditions.filter(item=>item.builtin);if(builtins.length&&!confirm(`Заменить предустановленные состояния на ${label}? Пользовательские состояния останутся.`))return;const existingByKey=new Map(builtins.map(item=>[conditionPresetMatchKey(item),item])),oldBuiltinsById=new Map(builtins.map(item=>[item.id,item])),nextByKey=new Map(preset.map(item=>[conditionPresetMatchKey(item),item.id])),custom=state.library.conditions.filter(item=>!item.builtin);state.rooms.forEach(room=>{if(!room.conditions||typeof room.conditions!=='object')return;for(const [entryId,ids] of Object.entries(room.conditions)){const next=(Array.isArray(ids)?ids:[]).map(id=>{const old=oldBuiltinsById.get(id);return old?(nextByKey.get(conditionPresetMatchKey(old))||null):id}).filter(Boolean);room.conditions[entryId]=[...new Set(next)];if(!room.conditions[entryId].length)delete room.conditions[entryId]}});state.library.conditions=[...preset.map(item=>({...cloneJson(item),tagIds:[...(existingByKey.get(conditionPresetMatchKey(item))?.tagIds||[])]})),...custom];state.library.conditionPreset=presetId;state.library.conditionPresetSystemVersion=CONDITION_PRESET_SYSTEM_VERSION;librarySearch.conditions='';libraryTagFilters.conditions.clear();save(`Предустановлены состояния ${label}`);render()}
function setLibraryTagSync(enabled){const library=state.library;if(Boolean(enabled)===library.syncTags)return;if(enabled){const mapping=new Map(),usedIds=new Set(state.tags.map(tag=>tag.id));for(const tag of library.tags){let target=state.tags.find(candidate=>candidate.name.trim().toLocaleLowerCase('ru')===tag.name.trim().toLocaleLowerCase('ru'));if(!target){let id=tag.id;if(usedIds.has(id))id=makeId();target={...tag,id};state.tags.push(target);usedIds.add(id)}mapping.set(tag.id,target.id)}for(const type of ['conditions','artifacts'])library[type].forEach(item=>item.tagIds=(item.tagIds||[]).map(id=>mapping.get(id)||id).filter(id=>state.tags.some(tag=>tag.id===id)));library.syncTags=true}else{library.tags=state.tags.map(tag=>({...tag}));library.syncTags=false}for(const type of ['conditions','artifacts'])libraryTagFilters[type].clear();save(enabled?'Теги Библиотеки синхронизированы с Бестиарием':'Для Библиотеки создан отдельный набор тегов')}
