    function removeRoomEntry(room,entryId){room.entries=room.entries.filter(entry=>entry.id!==entryId);delete room.initiatives[entryId];delete room.combatNotes[entryId];delete room.currentHp[entryId];if(room.bonusHp)delete room.bonusHp[entryId];if(room.conditions)delete room.conditions[entryId]}
    function renderRooms(){const cards=state.rooms.map((r,i)=>`<article class="card room-card" data-open-room="${r.id}" tabindex="0" role="button"><span class="card-kicker">Комната ${String(i+1).padStart(2,'0')}</span><h3>${escapeHtml(r.name)}</h3><p>${r.entries.length} ${plural(r.entries.length,'существо','существа','существ')}</p><div class="card-footer"><button class="mini" data-open-room="${r.id}">Открыть комнату</button></div></article>`).join('');el('content').innerHTML=`<header class="page-head"><div><p class="eyebrow">Игровые пространства</p><h1>Комнаты</h1><p class="lead">Выберите комнату или создайте новую.</p></div><div class="actions"><button class="button primary" id="new-room">＋ Создать комнату</button></div></header><section class="grid">${cards||empty('Комнат пока нет','Создайте первую комнату, а затем наполните её существами из бестиария.','Создать комнату','empty-room')}</section>`}
    function newRoomEntry(creatureId=null,npc=null){return{id:makeId(),creatureId,npc:creatureId?undefined:(npc||{name:'',description:'',hp:'',ac:'',characteristics:CHARACTERISTICS_TEMPLATE,abilities:'',notes:'',tagIds:[]})}}
    function openRoomDialog(id=null){editingRoomId=id;const room=roomById(id);el('room-dialog-title').textContent=room?'Настройки комнаты':'Новая комната';el('room-name').value=room?.name||'';const compactConditionAdd=el('room-compact-condition-add');if(compactConditionAdd)compactConditionAdd.checked=Boolean(room?.compactConditionAdd);el('delete-room').hidden=!room;el('room-dialog').showModal();setTimeout(()=>el('room-name').focus(),0)}
    function editRoomEntry(entryId){const room=roomById(view.roomId),entry=roomEntryById(room,entryId);if(!entry)return;el('detail-dialog').close();openCreatureDialog(entry.creatureId||null,entry.creatureId?null:entry.id)}
    function addNpcToBestiary(entryId){const room=roomById(view.roomId),entry=roomEntryById(room,entryId);if(!entry||entry.creatureId||!entry.npc)return;const creature={id:makeId(),...entry.npc,tagIds:[...(entry.npc.tagIds||[])]};state.bestiary.push(creature);entry.creatureId=creature.id;delete entry.npc;el('detail-dialog').close();save('NPC добавлен в Бестиарий');render()}
    function openMembership(id){membershipCreatureId=id;const c=creatureById(id);if(!c)return;membershipSelection=new Set(state.rooms.filter(r=>r.entries.some(entry=>entry.creatureId===id)).map(r=>r.id));el('membership-tools').hidden=true;el('membership-submit').textContent='Сохранить';el('membership-title').textContent=`Комнаты: ${c.name}`;el('membership-checks').innerHTML=state.rooms.length?state.rooms.map(r=>`<label class="check"><input type="checkbox" value="${r.id}" ${membershipSelection.has(r.id)?'checked':''}><span>${escapeHtml(r.name)}</span></label>`).join(''):`<div class="empty"><p>Сначала создайте хотя бы одну комнату.</p></div>`;el('membership-dialog').showModal()}
    function updateMembershipTagSummary(){const count=membershipTagFilters.size;el('membership-tag-summary').textContent=!count?'Все теги':count===1?state.tags.find(t=>membershipTagFilters.has(t.id))?.name||'1 тег':`${count} ${plural(count,'тег','тега','тегов')}`}
    function renderMembershipTagOptions(){el('membership-tag-options').innerHTML=`<label class="tag-option"><input id="membership-all-tags" type="checkbox" ${membershipTagFilters.size?'':'checked'}><span>Все теги</span></label>${state.tags.map(t=>`<label class="tag-option"><input type="checkbox" data-membership-tag="${t.id}" ${membershipTagFilters.has(t.id)?'checked':''}><span class="tag-check-dot" style="--tag-color:${validTagColor(t.color)}"></span><span>${escapeHtml(t.name)}</span></label>`).join('')}`;updateMembershipTagSummary()}
    function renderRoomMembershipOptions(){const room=roomById(view.roomId),list=state.bestiary.filter(c=>creatureMatchesQuery(c,membershipQuery)&&[...membershipTagFilters].every(id=>(c.tagIds||[]).includes(id)));el('membership-checks').innerHTML=list.length?list.map(c=>{const present=room?.entries.filter(entry=>entry.creatureId===c.id).length||0,pending=membershipPendingAdds.get(c.id)||0,count=[present?`В комнате: ${present}`:'',pending?`Добавится: ${pending}`:''].filter(Boolean).join(' · ');return `<div class="check add-copy-row"><div class="add-copy-info"><span class="add-copy-name">${escapeHtml(c.name)}</span>${count?`<span class="copy-count">${count}</span>`:''}</div><button class="add-copy-button" type="button" data-add-copy="${c.id}" aria-label="Добавить ещё одну копию ${escapeHtml(c.name)}" title="Добавить копию">＋</button></div>`}).join(''):`<div class="tag-editor-empty">${state.bestiary.length?'Ничего не найдено.':'Бестиарий пока пуст.'}</div>`}
    function openRoomMembership(){const room=roomById(view.roomId);if(!room)return;membershipCreatureId=null;membershipPendingAdds.clear();membershipQuery='';membershipTagFilters.clear();el('membership-title').textContent=`Существа: ${room.name}`;el('membership-tools').hidden=false;el('membership-submit').textContent='Добавить';el('membership-search').value='';el('membership-tag-select').open=false;renderMembershipTagOptions();renderRoomMembershipOptions();el('membership-dialog').showModal()}
