const ACCENT_KEY='initiative-accent-v1',ACCENT_THEMES={gold:{name:'Золотистый',color:'#d6a85f',description:'Его победит только могущественная сила... Железных мутантов.'},blue:{name:'Синий',color:'#4f9de8',description:'З..з...запалка...'},scarlet:{name:'Алый',color:'#ef5b56',description:'Рекомендовано Алым Успехом'},purple:{name:'Фиолетовый',color:'#a879e8',description:'Любимый цвет Пауки, поэтому и добавил'}};
    const FONT_KEY='initiative-display-font-v1',DISPLAY_FONTS={georgia:{name:'Georgia',style:'Georgia,serif'},neuzeit:{name:'Neuzeit Antiqua',style:"'Neuzeit Antiqua',Georgia,serif"},belarus:{name:'Belarus',style:"'Belarus',Georgia,serif"},ebbe:{name:'Ebbe Regular',style:"'Ebbe Regular','Ebbe',Georgia,serif"},'old-town':{name:'Old Town',style:"'Old Town',Georgia,serif"}};
    const BOLD_SECTIONS_KEY='initiative-bold-sections-v1',DENSITY_KEY='initiative-density-v1',COMBAT_TRACKING_KEY='initiative-combat-tracking-v1',BESTIARY_ADVANCED_SEARCH_KEY='initiative-bestiary-advanced-search-v1',JOURNAL_KEY='initiative-journal-v1',JOURNAL_SEARCH_KEY='initiative-journal-search-v1',JOURNAL_SECTIONS_KEY='initiative-journal-sections-v1',JOURNAL_BOLD_SECTIONS_KEY='initiative-journal-bold-sections-v1',BONUS_HP_KEY='initiative-bonus-hp-v1',BONUS_HP_CONTRAST_KEY='initiative-bonus-hp-contrast-v1',BONUS_HP_COLOR_KEY='initiative-bonus-hp-color-v1';
    function storedAccent(){try{const saved=localStorage.getItem(ACCENT_KEY);return ACCENT_THEMES[saved]?saved:'gold'}catch(_){return'gold'}}
    function applyAccent(theme,persist=true){accentTheme=ACCENT_THEMES[theme]?theme:'gold';document.documentElement.dataset.accent=accentTheme==='gold'?'':accentTheme;if(persist){try{localStorage.setItem(ACCENT_KEY,accentTheme)}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedDisplayFont(){try{const saved=localStorage.getItem(FONT_KEY),migrated=saved==='made-winter'?'old-town':saved;return DISPLAY_FONTS[migrated]?migrated:'georgia'}catch(_){return'georgia'}}
    function applyDisplayFont(font,persist=true){displayFont=DISPLAY_FONTS[font]?font:'georgia';document.documentElement.dataset.font=displayFont==='georgia'?'':displayFont;if(persist){try{localStorage.setItem(FONT_KEY,displayFont)}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedBoldSections(){try{return localStorage.getItem(BOLD_SECTIONS_KEY)==='true'}catch(_){return false}}
    function applyBoldSections(enabled,persist=true){boldAsSection=Boolean(enabled);if(persist){try{localStorage.setItem(BOLD_SECTIONS_KEY,String(boldAsSection))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedInterfaceDensity(){try{const value=Number(localStorage.getItem(DENSITY_KEY));return Number.isInteger(value)&&value>=0&&value<=2?value:0}catch(_){return 0}}
    function applyInterfaceDensity(value,persist=true){const numeric=Math.max(0,Math.min(2,Math.trunc(Number(value)||0)));interfaceDensity=numeric;document.documentElement.dataset.density=numeric?String(numeric):'';if(persist){try{localStorage.setItem(DENSITY_KEY,String(interfaceDensity))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    
    function storedCombatTracking(){try{return localStorage.getItem(COMBAT_TRACKING_KEY)==='true'}catch(_){return false}}
    function applyCombatTracking(enabled,persist=true){combatTrackingEnabled=Boolean(enabled);if(persist){try{localStorage.setItem(COMBAT_TRACKING_KEY,String(combatTrackingEnabled))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedBestiaryAdvancedSearch(){try{return localStorage.getItem(BESTIARY_ADVANCED_SEARCH_KEY)==='true'}catch(_){return false}}
    function applyBestiaryAdvancedSearch(enabled,persist=true){bestiaryAdvancedSearch=Boolean(enabled);if(persist){try{localStorage.setItem(BESTIARY_ADVANCED_SEARCH_KEY,String(bestiaryAdvancedSearch))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedJournalEnabled(){try{return localStorage.getItem(JOURNAL_KEY)==='true'}catch(_){return false}}
    function applyJournalEnabled(enabled,persist=true){journalEnabled=Boolean(enabled);if(persist){try{localStorage.setItem(JOURNAL_KEY,String(journalEnabled))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedJournalSearch(){try{return localStorage.getItem(JOURNAL_SEARCH_KEY)==='true'}catch(_){return false}}
    function applyJournalSearch(enabled,persist=true){journalSearchEnabled=Boolean(enabled);if(persist){try{localStorage.setItem(JOURNAL_SEARCH_KEY,String(journalSearchEnabled))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedJournalSections(){try{return localStorage.getItem(JOURNAL_SECTIONS_KEY)==='true'}catch(_){return false}}
    function applyJournalSections(enabled,persist=true){journalSectionsEnabled=Boolean(enabled);if(persist){try{localStorage.setItem(JOURNAL_SECTIONS_KEY,String(journalSectionsEnabled))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedJournalBoldSections(){try{return localStorage.getItem(JOURNAL_BOLD_SECTIONS_KEY)==='true'}catch(_){return false}}
    function applyJournalBoldSections(enabled,persist=true){journalBoldSections=Boolean(enabled);if(persist){try{localStorage.setItem(JOURNAL_BOLD_SECTIONS_KEY,String(journalBoldSections))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedBonusHpEnabled(){try{return localStorage.getItem(BONUS_HP_KEY)==='true'}catch(_){return false}}
    function applyBonusHpEnabled(enabled,persist=true){bonusHpEnabled=Boolean(enabled);if(persist){try{localStorage.setItem(BONUS_HP_KEY,String(bonusHpEnabled))}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    function storedBonusHpContrast(){try{return localStorage.getItem(BONUS_HP_CONTRAST_KEY)==='true'}catch(_){return false}}
    function storedBonusHpColor(){try{const saved=localStorage.getItem(BONUS_HP_COLOR_KEY);return ACCENT_THEMES[saved]?saved:'gold'}catch(_){return'gold'}}
    function applyBonusHpStyle(contrast,color,persist=true){bonusHpContrast=Boolean(contrast);bonusHpColor=ACCENT_THEMES[color]?color:'gold';const root=document.documentElement;if(bonusHpContrast){const hex=ACCENT_THEMES[bonusHpColor].color,r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);root.style.setProperty('--bonus-hp-accent',hex);root.style.setProperty('--bonus-hp-border',`rgba(${r},${g},${b},.58)`);root.style.setProperty('--bonus-hp-panel',`rgba(${r},${g},${b},.16)`);root.style.setProperty('--bonus-hp-input',`rgba(${r},${g},${b},.09)`);root.style.setProperty('--bonus-hp-text',`rgb(${Math.min(255,r+45)},${Math.min(255,g+45)},${Math.min(255,b+45)})`);root.style.setProperty('--bonus-hp-placeholder',`rgba(${r},${g},${b},.58)`);root.style.setProperty('--bonus-hp-glow',`rgba(${r},${g},${b},.18)`)}else['--bonus-hp-accent','--bonus-hp-border','--bonus-hp-panel','--bonus-hp-input','--bonus-hp-text','--bonus-hp-placeholder','--bonus-hp-glow'].forEach(name=>root.style.removeProperty(name));if(persist){try{localStorage.setItem(BONUS_HP_CONTRAST_KEY,String(bonusHpContrast));localStorage.setItem(BONUS_HP_COLOR_KEY,bonusHpColor)}catch(_){}markLocalMutation(false);scheduleCloudSave()}}
    let accentTheme=storedAccent(),displayFont=storedDisplayFont(),boldAsSection=storedBoldSections(),interfaceDensity=storedInterfaceDensity(),combatTrackingEnabled=storedCombatTracking(),bestiaryAdvancedSearch=storedBestiaryAdvancedSearch(),journalEnabled=storedJournalEnabled(),journalSearchEnabled=storedJournalSearch(),journalSectionsEnabled=storedJournalSections(),journalBoldSections=storedJournalBoldSections(),bonusHpEnabled=storedBonusHpEnabled(),bonusHpContrast=storedBonusHpContrast(),bonusHpColor=storedBonusHpColor();applyAccent(accentTheme,false);applyDisplayFont(displayFont,false);applyBoldSections(boldAsSection,false);applyInterfaceDensity(interfaceDensity,false);applyCombatTracking(combatTrackingEnabled,false);applyBestiaryAdvancedSearch(bestiaryAdvancedSearch,false);applyJournalEnabled(journalEnabled,false);applyJournalSearch(journalSearchEnabled,false);applyJournalSections(journalSectionsEnabled,false);applyJournalBoldSections(journalBoldSections,false);applyBonusHpEnabled(bonusHpEnabled,false);applyBonusHpStyle(bonusHpContrast,bonusHpColor,false);

let settingsSection='interface';
    function renderSettings(){
      const allowed=new Set(['interface','bestiary','rooms','journal','data']);if(!allowed.has(settingsSection))settingsSection='interface';
      const choices=Object.entries(ACCENT_THEMES).map(([id,theme])=>`<button class="accent-choice ${accentTheme===id?'current':''}" data-accent-choice="${id}" style="--choice:${theme.color}" aria-pressed="${accentTheme===id}"><span class="accent-swatch" aria-hidden="true"></span><span class="accent-copy"><strong>${theme.name}</strong><span>${theme.description}</span></span><span class="accent-state">${accentTheme===id?'Выбрано':''}</span></button>`).join(''),
        fonts=Object.entries(DISPLAY_FONTS).map(([id,font])=>`<button class="font-choice ${displayFont===id?'current':''}" data-font-choice="${id}" aria-pressed="${displayFont===id}"><span class="font-copy"><strong>${font.name}</strong><span class="font-sample" style="font-family:${font.style}">Трекер инициативы</span></span><span class="font-state">${displayFont===id?'Выбрано':''}</span></button>`).join(''),
        bonusColors=Object.entries(ACCENT_THEMES).map(([id,theme])=>`<button class="bonus-color-choice ${bonusHpColor===id?'current':''}" type="button" data-bonus-color="${id}" style="--choice:${theme.color}" aria-pressed="${bonusHpColor===id}"><span class="bonus-color-swatch" aria-hidden="true"></span>${theme.name}</button>`).join(''),
        tabs=[['interface','Интерфейс'],['bestiary','Бестиарий'],['rooms','Комнаты'],['journal','Журнал'],['data','Данные']],
        nav=tabs.map(([id,label])=>`<button class="settings-nav-button ${settingsSection===id?'current':''}" type="button" data-settings-section="${id}" aria-pressed="${settingsSection===id}">${label}</button>`).join('');
      let panel='';
      if(settingsSection==='interface')panel=`<div class="settings-panel-head"><h2>Интерфейс</h2><p>Цветовая тема, шрифт и плотность интерфейса.</p></div><h3 class="settings-section-title">Компактность</h3><section class="density-settings"><div class="density-copy"><strong>Плотность интерфейса</strong><span>Меняет отступы, промежутки и высоты элементов, не уменьшая текст.</span></div><div class="density-control"><input id="interface-density" type="range" min="0" max="2" step="1" value="${interfaceDensity}" aria-label="Компактность интерфейса"><output id="interface-density-label" for="interface-density">${['Обычная','Компактная','Плотная'][interfaceDensity]}</output></div></section><h3 class="settings-section-title">Контрастный цвет</h3><section class="settings-grid" aria-label="Контрастный цвет интерфейса">${choices}</section><h3 class="settings-section-title">Шрифт заголовков</h3><section class="font-grid" aria-label="Шрифт заголовков интерфейса">${fonts}</section>`;
      if(settingsSection==='bestiary')panel=`<div class="settings-panel-head"><h2>Бестиарий</h2><p>Поведение поиска и навигации по карточкам существ.</p></div><section class="bonus-settings bestiary-settings"><label class="advanced-setting" for="bestiary-advanced-search"><span class="advanced-copy"><strong>Расширенный поиск</strong><span>Искать по имени, описанию, характеристикам, способностям, заметкам и названиям тегов.</span></span><span class="advanced-toggle"><input id="bestiary-advanced-search" type="checkbox" ${bestiaryAdvancedSearch?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label><label class="advanced-setting" for="bold-as-section"><span class="advanced-copy"><strong>Считать жирный текст разделом карточки</strong><span>Добавлять выделенный жирным текст в меню навигации карточки существа.</span></span><span class="advanced-toggle"><input id="bold-as-section" type="checkbox" ${boldAsSection?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label></section>`;
      if(settingsSection==='rooms')panel=`<div class="settings-panel-head"><h2>Комнаты</h2><p>Настройки инициативы, активного хода и отображения здоровья.</p></div><section class="bonus-settings rooms-settings"><label class="advanced-setting" for="combat-tracking"><span class="advanced-copy"><strong>Отслеживание активного существа</strong><span>После нажатия «Следующий ход» центрировать экран на активном существе.</span></span><span class="advanced-toggle"><input id="combat-tracking" type="checkbox" ${combatTrackingEnabled?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label><label class="advanced-setting" for="bonus-hp-enabled"><span class="advanced-copy"><strong>Отдельные бонусные хиты</strong><span>Показывать перед обычными ХП независимый трекер бонусных хитов.</span></span><span class="advanced-toggle"><input id="bonus-hp-enabled" type="checkbox" ${bonusHpEnabled?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label>${bonusHpEnabled?`<label class="advanced-setting" for="bonus-hp-contrast"><span class="advanced-copy"><strong>Контрастный цвет бонусных хитов</strong><span>Вместо стандартного голубого использовать отдельный выбранный цвет.</span></span><span class="advanced-toggle"><input id="bonus-hp-contrast" type="checkbox" ${bonusHpContrast?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label>${bonusHpContrast?`<div class="bonus-color-options" role="group" aria-label="Цвет бонусных хитов">${bonusColors}</div>`:''}`:''}</section>`;
      if(settingsSection==='journal')panel=`<div class="settings-panel-head"><h2>Журнал</h2><p>Включение Журнала, поиск и навигация по его разделам.</p></div><section class="bonus-settings journal-settings"><label class="advanced-setting" for="journal-enabled"><span class="advanced-copy"><strong>Включить Журнал</strong><span>Показывать заметки прямо в комнате.</span></span><span class="advanced-toggle"><input id="journal-enabled" type="checkbox" ${journalEnabled?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label>${journalEnabled?`<label class="advanced-setting" for="journal-search-enabled"><span class="advanced-copy"><strong>Включить поиск</strong><span>Показывать строку поиска при открытии Журнала.</span></span><span class="advanced-toggle"><input id="journal-search-enabled" type="checkbox" ${journalSearchEnabled?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label><label class="advanced-setting" for="journal-sections-enabled"><span class="advanced-copy"><strong>Включить разделы</strong><span>Показывать меню быстрого перехода к заголовкам.</span></span><span class="advanced-toggle"><input id="journal-sections-enabled" type="checkbox" ${journalSectionsEnabled?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label><label class="advanced-setting" for="journal-bold-sections"><span class="advanced-copy"><strong>Считать жирный текст разделом</strong><span>Добавлять жирный текст в меню разделов только в Журнале.</span></span><span class="advanced-toggle"><input id="journal-bold-sections" type="checkbox" ${journalBoldSections?'checked':''}><span class="advanced-toggle-track" aria-hidden="true"></span></span></label>`:''}</section>`;
      if(settingsSection==='data')panel=`<div class="settings-panel-head"><h2>Данные</h2><p>Резервные копии всего локального архива WreckTrack.</p></div><section class="backup-settings"><div class="backup-settings-copy"><strong>Резервная копия приложения</strong><span>Сохранить Бестиарий, комнаты, текущие значения боя, Журнал и настройки одним JSON-файлом.</span></div><div class="backup-actions"><button class="button primary" id="create-full-backup" type="button">Создать резервную копию</button><button class="button" id="restore-full-backup" type="button">Восстановить из копии</button></div></section>`;
      el('content').innerHTML=`<header class="page-head"><div><p class="eyebrow">Параметры приложения</p><h1>Настройки</h1></div></header><div class="settings-layout"><nav class="settings-nav" aria-label="Разделы настроек">${nav}</nav><section class="settings-panel">${panel}</section></div>`
    }
