    function registerTokenatorEvents(){
    document.addEventListener('click',e=>{const frame=e.target.closest('[data-token-frame]'),deleteColor=e.target.closest('[data-token-color-delete]'),savedColor=e.target.closest('[data-token-color]');if(frame){tokenatorFrame=frame.dataset.tokenFrame;renderTokenator();return}if(deleteColor){const color=deleteColor.dataset.tokenColorDelete;tokenatorFavoriteColors=tokenatorFavoriteColors.filter(saved=>saved!==color);persistTokenColors();markLocalMutation(false);scheduleCloudSave();renderTokenator();showToast('Цвет удалён из закладок');return}if(savedColor){setTokenatorCustomColor(savedColor.dataset.tokenColor);renderTokenator();return}if(e.target.closest('#tokenator-save-color')){if(!authSession?.user){openAuthDialog();return}if(!tokenatorFavoriteColors.includes(tokenatorCustomColor)){tokenatorFavoriteColors=[...tokenatorFavoriteColors,tokenatorCustomColor].slice(-12);persistTokenColors();markLocalMutation(false);scheduleCloudSave();showToast('Цвет добавлен в закладки')}else showToast('Этот цвет уже в закладках');renderTokenator();return}if(e.target.closest('#tokenator-reset')){resetTokenatorTransform();return}if(e.target.closest('#tokenator-download')){downloadToken();return}if(e.target.closest('#tokenator-upload')){openTokenatorFile();return}if(e.target.closest('#tokenator-dropzone')&&!tokenatorDragged)openTokenatorFile();tokenatorDragged=false})
    document.addEventListener('keydown',e=>{if(!e.target.closest('#tokenator-dropzone')||!['Enter',' '].includes(e.key))return;e.preventDefault();openTokenatorFile()})
    document.addEventListener('input',e=>{if(e.target.id==='tokenator-scale'){tokenatorScale=Number(e.target.value)/100;const output=el('tokenator-scale-value');if(output)output.value=`${e.target.value}%`;scheduleTokenatorDraw();return}if(e.target.id==='tokenator-custom-color'){setTokenatorCustomColor(e.target.value);return}if(e.target.id==='tokenator-custom-code'){const color=normalizeTokenColor(e.target.value);if(color)setTokenatorCustomColor(color)}})
    document.addEventListener('change',e=>{if(e.target.id==='tokenator-custom-code'){if(!setTokenatorCustomColor(e.target.value,true))e.target.value=tokenatorCustomColor.toUpperCase();return}if(e.target.id!=='tokenator-file')return;const file=e.target.files?.[0];if(file)loadTokenatorImage(file);e.target.value=''})
    document.addEventListener('paste',e=>{if(view.name!=='tokenator')return;const target=e.target;if(target?.closest?.('input,textarea,select,[contenteditable="true"]'))return;const items=[...(e.clipboardData?.items||[])],imageItem=items.find(item=>item.kind==='file'&&/^image\/(png|jpeg|webp)$/.test(item.type));if(!imageItem)return;const file=imageItem.getAsFile();if(!file)return;e.preventDefault();loadTokenatorImage(file,'Изображение вставлено')})
    document.addEventListener('wheel',e=>{const zone=e.target.closest?.('#tokenator-dropzone');if(!zone||!tokenatorPortrait)return;e.preventDefault();const previous=tokenatorScale,next=Math.min(2.5,Math.max(.7,previous+(e.deltaY<0?.05:-.05)));if(next===previous)return;const rect=zone.getBoundingClientRect(),factor=1100/rect.width,cursorX=(e.clientX-rect.left)*factor,cursorY=(e.clientY-rect.top)*factor,ratio=next/previous,centerX=548.5,centerY=550.5;tokenatorOffsetX=ratio*tokenatorOffsetX+(1-ratio)*(cursorX-centerX);tokenatorOffsetY=ratio*tokenatorOffsetY+(1-ratio)*(cursorY-centerY);tokenatorScale=next;const slider=el('tokenator-scale'),output=el('tokenator-scale-value'),percent=Math.round(next*100);if(slider)slider.value=percent;if(output)output.value=`${percent}%`;scheduleTokenatorDraw()},{passive:false})
    document.addEventListener('pointerdown',e=>{const zone=e.target.closest('#tokenator-dropzone');if(!zone||!tokenatorPortrait)return;tokenatorDrag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:tokenatorOffsetX,startY:tokenatorOffsetY};tokenatorDragged=false;zone.setPointerCapture(e.pointerId);zone.classList.add('dragging')})
    document.addEventListener('pointermove',e=>{if(!tokenatorDrag||e.pointerId!==tokenatorDrag.id)return;const zone=el('tokenator-dropzone'),factor=1100/zone.getBoundingClientRect().width,dx=(e.clientX-tokenatorDrag.x)*factor,dy=(e.clientY-tokenatorDrag.y)*factor;if(Math.hypot(dx,dy)>4)tokenatorDragged=true;tokenatorOffsetX=tokenatorDrag.startX+dx;tokenatorOffsetY=tokenatorDrag.startY+dy;scheduleTokenatorDraw()})
    document.addEventListener('pointerup',e=>{if(!tokenatorDrag||e.pointerId!==tokenatorDrag.id)return;el('tokenator-dropzone')?.classList.remove('dragging');tokenatorDrag=null})
    document.addEventListener('pointercancel',()=>{el('tokenator-dropzone')?.classList.remove('dragging');tokenatorDrag=null})
    }
