    function registerPrimaryFormEvents(){
    el('room-form').addEventListener('submit',e=>{e.preventDefault();const name=el('room-name').value.trim(),compactConditionAdd=Boolean(el('room-compact-condition-add')?.checked);if(!name)return;if(editingRoomId){const room=roomById(editingRoomId);room.name=name;room.compactConditionAdd=compactConditionAdd;save('Комната изменена')}else{state.rooms.push({id:makeId(),name,journal:'',compactConditionAdd,entries:[],initiatives:{},combatNotes:{},currentHp:{},bonusHp:{},conditions:{},combat:{active:false,round:1,turnCreatureId:null}});save('Комната создана')}el('room-dialog').close();render()})
    el('creature-form').addEventListener('submit',e=>{e.preventDefault();const creature={name:el('creature-name').value.trim(),description:el('creature-description').value.trim(),hp:el('creature-hp').value.trim(),ac:el('creature-ac').value.trim(),characteristics:el('creature-characteristics').value.trim(),abilities:el('creature-abilities').value.trim(),notes:el('creature-notes').value.trim(),tagIds:[...el('creature-tag-checks').querySelectorAll('input:checked')].map(x=>x.value)};if(!creature.name)return;const room=roomById(view.roomId);if(creatingNpcForRoom&&room){room.entries.push(newRoomEntry(null,creature));save('NPC создан')}else if(editingRoomEntryId&&room){const entry=roomEntryById(room,editingRoomEntryId);if(entry?.npc){Object.assign(entry.npc,creature);save('NPC изменён')}}else if(editingCreatureId){Object.assign(creatureById(editingCreatureId),creature);save('Существо изменено')}else{state.bestiary.push({id:makeId(),...creature});save('Существо создано')}el('creature-dialog').close();render()})
    el('tags-form').addEventListener('submit',e=>{e.preventDefault();tagDraft=tagDraft.map(t=>({...t,name:t.name.trim().slice(0,30),color:validTagColor(t.color)})).filter(t=>t.name);const kept=new Set(tagDraft.map(t=>t.id)),libraryScope=tagEditorScope==='library'&&!state.library.syncTags;if(libraryScope){state.library.tags=tagDraft;for(const type of ['conditions','artifacts'])state.library[type].forEach(item=>item.tagIds=(item.tagIds||[]).filter(id=>kept.has(id)));for(const type of ['conditions','artifacts'])libraryTagFilters[type].forEach(id=>{if(!kept.has(id))libraryTagFilters[type].delete(id)});save('Теги Библиотеки сохранены')}else{state.tags=tagDraft;state.bestiary.forEach(c=>c.tagIds=(c.tagIds||[]).filter(id=>kept.has(id)));state.rooms.forEach(r=>r.entries.forEach(entry=>{if(entry.npc)entry.npc.tagIds=(entry.npc.tagIds||[]).filter(id=>kept.has(id))}));bestiaryTagFilters.forEach(id=>{if(!kept.has(id))bestiaryTagFilters.delete(id)});if(state.library.syncTags){for(const type of ['conditions','artifacts']){state.library[type].forEach(item=>item.tagIds=(item.tagIds||[]).filter(id=>kept.has(id)));libraryTagFilters[type].forEach(id=>{if(!kept.has(id))libraryTagFilters[type].delete(id)})}}save(tagEditorScope==='library'?'Общие теги Библиотеки и Бестиария сохранены':'Теги сохранены')}tagEditorScope='bestiary';el('tags-dialog').close();render()})
    el('membership-form').addEventListener('submit',e=>{e.preventDefault();if(membershipCreatureId){const selected=[...membershipSelection];state.rooms.forEach(r=>{const kept=selected.includes(r.id),matches=r.entries.filter(entry=>entry.creatureId===membershipCreatureId);if(kept&&!matches.length)r.entries.push(newRoomEntry(membershipCreatureId));if(!kept)matches.forEach(entry=>removeRoomEntry(r,entry.id))});save('Состав комнат обновлён')}else{const room=roomById(view.roomId),total=[...membershipPendingAdds.values()].reduce((sum,count)=>sum+count,0);if(room&&total){membershipPendingAdds.forEach((count,creatureId)=>{for(let i=0;i<count;i++)room.entries.push(newRoomEntry(creatureId))});save(`${total} ${plural(total,'существо добавлено','существа добавлены','существ добавлено')}`)}}el('membership-dialog').close();render()})
    el('export-form').addEventListener('submit',e=>{e.preventDefault();downloadSelectedCreatures()})
    el('auth-form').addEventListener('submit',e=>e.preventDefault())
    el('import-creatures-file').addEventListener('change',async e=>{const file=e.target.files?.[0];e.target.value='';await importCreaturesFile(file)})
    el('import-preview-dialog').addEventListener('close',()=>{pendingCreatureImport=null})
    el('import-lss-character-file').addEventListener('change',async e=>{const file=e.target.files?.[0];e.target.value='';await importLssCharacterFile(file)})
    }
