// Shared Markdown editing controls for textarea-based editors.
// Keep these helpers state-agnostic: feature modules decide when to invoke them.

function wrapMarkdown(area,before,after,placeholder){const start=area.selectionStart,end=area.selectionEnd,selected=area.value.slice(start,end)||placeholder;area.setRangeText(before+selected+after,start,end,'end');area.focus();area.setSelectionRange(start+before.length,start+before.length+selected.length);area.dispatchEvent(new Event('input',{bubbles:true}))}

function addMarkdownToolbars(){document.querySelectorAll('textarea[data-markdown]').forEach(area=>{if(area.previousElementSibling?.classList.contains('markdown-toolbar'))return;const label=area.closest('.field')?.querySelector('label')?.textContent?.trim()||'текста';area.insertAdjacentHTML('beforebegin',`<div class="markdown-toolbar" data-markdown-toolbar="${area.id}" role="toolbar" aria-label="Форматирование ${escapeHtml(label.toLowerCase())}"><button class="markdown-tool markdown-tool-bold" type="button" data-markdown-format="bold" aria-label="Жирный" title="Жирный">B</button><button class="markdown-tool markdown-tool-italic" type="button" data-markdown-format="italic" aria-label="Курсив" title="Курсив">I</button><button class="markdown-tool markdown-tool-strike" type="button" data-markdown-format="strike" aria-label="Зачёркнутый" title="Зачёркнутый">S</button><button class="markdown-tool markdown-tool-task" type="button" data-markdown-format="task" aria-label="Чекбокс" title="Чекбокс">☑</button><button class="markdown-tool markdown-tool-resource" type="button" data-markdown-format="resource" aria-label="Ресурс" title="Ресурс">◇</button></div>`)})}

function prefixMarkdownLines(area,prefix,type){const value=area.value,start=area.selectionStart,end=area.selectionEnd,lineStart=value.lastIndexOf('\n',Math.max(0,start-1))+1,nextBreak=value.indexOf('\n',end),lineEnd=nextBreak===-1?value.length:nextBreak,lines=value.slice(lineStart,lineEnd).split('\n'),pattern=type==='heading'?/^#{1,6}\s+/:/^\s*[-*]\s+/,allMatch=lines.every(line=>type==='heading'?line.startsWith(prefix):pattern.test(line)),changed=lines.map(line=>{const clean=line.replace(pattern,'');return allMatch?clean:prefix+clean}).join('\n');area.setRangeText(changed,lineStart,lineEnd,'select');area.focus();area.dispatchEvent(new Event('input',{bubbles:true}))}

function toggleMarkdownTask(area){const value=area.value,start=area.selectionStart,end=area.selectionEnd,lineStart=value.lastIndexOf('\n',Math.max(0,start-1))+1,nextBreak=value.indexOf('\n',end),lineEnd=nextBreak===-1?value.length:nextBreak,lines=value.slice(lineStart,lineEnd).split('\n'),allTasks=lines.every(line=>/^\s*[-*]\s+\[[ xX]\]\s?/.test(line)),changed=lines.map(line=>allTasks?line.replace(/^\s*[-*]\s+\[[ xX]\]\s?/,''):'- [ ] '+line).join('\n');area.setRangeText(changed,lineStart,lineEnd,'select');area.focus();area.dispatchEvent(new Event('input',{bubbles:true}))}

function insertMarkdownResource(area){const start=area.selectionStart,end=area.selectionEnd,selected=area.value.slice(start,end);area.setRangeText('[ ] '+selected,start,end,'end');area.focus();area.setSelectionRange(start+4+selected.length,start+4+selected.length);area.dispatchEvent(new Event('input',{bubbles:true}))}
