    const CHARACTERISTICS_TEMPLATE='С:0 | Л:0 | Т:0 | И:0 | М:0 | X:0';
        let state=loadState(),view={name:'home',roomId:null},editingRoomId=null,editingCreatureId=null,editingRoomEntryId=null,creatingNpcForRoom=false,membershipCreatureId=null,membershipSelection=new Set(),membershipPendingAdds=new Map(),membershipQuery='',membershipTagFilters=new Set(),tagDraft=[],draggedTagId=null,bestiaryQuery='',bestiaryTagFilters=new Set(),bestiarySort='number',exportQuery='',exportSelection=new Set(),pendingCreatureImport=null;



    const creatureById=id=>state.bestiary.find(c=>c.id===id),roomById=id=>state.rooms.find(r=>r.id===id);
    const entryCreature=entry=>entry?.creatureId?creatureById(entry.creatureId):entry?.npc;
    const roomEntryById=(room,id)=>room?.entries.find(entry=>entry.id===id);
    const roomCountForCreature=id=>state.rooms.filter(r=>r.entries.some(entry=>entry.creatureId===id)).length;
    function go(name,roomId=null,{fromHistory=false}={}){view={name,roomId};if(!fromHistory){const next={...(history.state||{}),archiveView:name==='home'?'home':'content'};if(name!=='home'&&history.state?.archiveView!=='content')history.pushState(next,'');else history.replaceState(next,'')}render();scrollTo({top:0,behavior:'smooth'})}
    function empty(title,text,button,id){return `<div class="empty"><div class="empty-symbol">◇</div><h3>${title}</h3><p>${text}</p>${button?`<button class="button primary" id="${id}">${button}</button>`:''}</div>`}
        function render(){el('back-home').hidden=view.name==='home';if(view.name==='home')renderHome();if(view.name==='bestiary')renderBestiary();if(view.name==='rooms')renderRooms();if(view.name==='room')renderRoom();if(view.name==='settings')renderSettings();if(view.name==='tokenator')renderTokenator()}
    function renderHome(){el('content').innerHTML=`<section><p class="eyebrow">Личный архив</p><h1>Что вы хотите открыть?</h1><p class="lead">Бестиарий хранит всех существ. Комнаты собирают нужных существ для отдельных игр и сцен.</p><div class="home-grid"><button class="portal" data-go="bestiary"><span class="portal-index">РАЗДЕЛ 01</span><span class="portal-arrow">→</span><h2>Бестиарий</h2><p>${state.bestiary.length} ${plural(state.bestiary.length,'существо','существа','существ')} в общей библиотеке</p></button><button class="portal" data-go="rooms"><span class="portal-index">РАЗДЕЛ 02</span><span class="portal-arrow">→</span><h2>Комнаты</h2><p>${state.rooms.length} ${plural(state.rooms.length,'комната','комнаты','комнат')} для игр и сцен</p></button><button class="portal tokenator-portal" data-go="tokenator"><span class="portal-index">РАЗДЕЛ 03</span><span class="portal-arrow">→</span><h2>Токенатор</h2><p>Создание токенов для игрового стола</p></button></div></section>`}
    registerSettingsNavigationEvents();
    registerBestiaryCreateEvent();
    registerSettingsChoiceEvents();
    registerTokenatorEvents();
    registerDetailControlEvents();
    registerPrimaryFormEvents();
    registerBestiaryCardEvents();
    registerSettingsToggleEvents();
    registerBonusHpEvents();
    registerPrimaryActionEvents();
    registerMenuDismissEvents();
    registerDataFileEvents();
    registerMixedInputEvents();
    registerBattleNotePreviewEvents();
    registerMixedChangeEvents();
    createJournalDialog();
    
    addMarkdownToolbars();
    
        
    
document.addEventListener('pointerdown',e=>{if(e.target.closest('[data-markdown-format],[data-journal-format]'))e.preventDefault()})
    document.addEventListener('click',e=>{if(e.target.closest('#open-journal'))openJournal()})
    document.addEventListener('click',e=>{if(!e.target.closest('#toggle-outside-combat'))return;const room=roomById(view.roomId);if(!room)return;room.outsideCombatCollapsed=!room.outsideCombatCollapsed;save();render()})
    document.addEventListener('click',e=>{const format=e.target.closest('[data-journal-format]');if(format){const type=format.dataset.journalFormat;if(type==='task'||type==='resource')insertJournalControl(type);else wrapJournalMarkdown(type);return}const search=e.target.closest('[data-journal-search]');if(search){moveJournalSearch(Number(search.dataset.journalSearch));return}const jump=e.target.closest('[data-journal-line-jump]');if(jump){const index=Number(jump.dataset.journalLineJump);journalTocActiveLine=index;activateJournalLine(index);el('journal-live-editor')?.querySelector(`[data-journal-line="${index}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}})
    document.addEventListener('click',e=>{const button=e.target.closest('[data-markdown-format]');if(!button)return;const area=el(button.closest('[data-markdown-toolbar]')?.dataset.markdownToolbar);if(!area)return;const type=button.dataset.markdownFormat,formats={bold:['**','**','жирный текст'],italic:['*','*','курсив'],strike:['~~','~~','зачёркнутый текст']},format=formats[type];if(format)wrapMarkdown(area,...format);else if(type==='task')toggleMarkdownTask(area);else if(type==='resource')insertMarkdownResource(area)})
    document.addEventListener('keydown',e=>{const area=e.target.closest('textarea[data-markdown]');if(area&&(e.ctrlKey||e.metaKey)){const key=e.key.toLowerCase();if(key==='b'){e.preventDefault();wrapMarkdown(area,'**','**','жирный текст');return}if(key==='i'){e.preventDefault();wrapMarkdown(area,'*','*','курсив');return}if(key==='e'){e.preventDefault();wrapMarkdown(area,'`','`','код');return}if(/^[1-6]$/.test(key)&&!e.shiftKey){e.preventDefault();prefixMarkdownLines(area,'#'.repeat(Number(key))+' ','heading');return}if(e.shiftKey&&e.code==='Digit8'){e.preventDefault();prefixMarkdownLines(area,'- ','list');return}}const card=e.target.closest('.room-card');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();go('room',card.dataset.openRoom)}})
    registerBattleNoteMenuEvents();
    window.addEventListener('offline',()=>{networkOnline=false;clearTimeout(cloudSaveTimer);if(authSession?.user){if(cloudSyncState==='saving'||cloudSaveQueued)cloudPendingChanges=true;cloudSyncState='offline'}updateCloudStatus()})
    window.addEventListener('online',()=>{networkOnline=true;if(!authSession?.user){updateCloudStatus();return}showToast('Соединение восстановлено — синхронизируем данные');retryCloudSync()})
    document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='hidden')return;persistLocalState();if(cloudSyncState==='saving')saveCloudNow()})
    window.addEventListener('pagehide',persistLocalState)
    window.addEventListener('popstate',()=>{if(view.name!=='home')go('home',null,{fromHistory:true})})
    el('brand-home').onclick=()=>go('home');el('back-home').onclick=()=>go('home');document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;if(d.id==='journal-dialog'){requestCloseJournal();return}if(d.id==='import-preview-dialog')pendingCreatureImport=null;d.close()}))
    window.archiveActions={createRoom:name=>{const clean=String(name||'').trim();if(!clean)throw Error('Название обязательно');const room={id:makeId(),name:clean,entries:[],initiatives:{},combatNotes:{},currentHp:{},combat:{active:false,round:1,turnCreatureId:null}};state.rooms.push(room);save();render();return room},createCreature:(name,notes='')=>{const clean=String(name||'').trim();if(!clean)throw Error('Имя обязательно');const c={id:makeId(),name:clean,description:'',hp:'',ac:'',characteristics:CHARACTERISTICS_TEMPLATE,abilities:'',notes:String(notes),tagIds:[]};state.bestiary.push(c);save();render();return c},addCreatureToRoom:(creatureId,roomId)=>{const c=creatureById(creatureId),r=roomById(roomId);if(!c||!r)throw Error('Существо или комната не найдены');const entry=newRoomEntry(c.id);r.entries.push(entry);save();render();return{creature:c.name,room:r.name,entryId:entry.id}},setInitiative:(creatureId,roomId,value)=>{const c=creatureById(creatureId),r=roomById(roomId),entry=r?.entries.find(item=>item.creatureId===creatureId);if(!c||!r||!entry)throw Error('Участник комнаты не найден');r.initiatives[entry.id]=Math.max(-99,Math.min(999,Math.trunc(Number(value)||0)));save();render();return{creature:c.name,room:r.name,initiative:r.initiatives[entry.id],entryId:entry.id}}}
    function registerAgentTools(){const context=document.modelContext;if(!context?.registerTool)return;const reg=t=>{try{Promise.resolve(context.registerTool(t)).catch(()=>{})}catch(_){}};reg({name:'create_room',title:'Создать комнату',description:'Создаёт отдельную игровую комнату.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:60}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>{const r=window.archiveActions.createRoom(i?.name);return{id:r.id,name:r.name}}});reg({name:'create_bestiary_creature',title:'Создать существо',description:'Создаёт существо в общем бестиарии.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:80},notes:{type:'string',maxLength:3000}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>{const c=window.archiveActions.createCreature(i?.name,i?.notes||'');return{id:c.id,name:c.name}}});reg({name:'add_creature_to_room',title:'Добавить существо в комнату',description:'Добавляет существо из бестиария в комнату.',inputSchema:{type:'object',properties:{creatureId:{type:'string'},roomId:{type:'string'}},required:['creatureId','roomId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>window.archiveActions.addCreatureToRoom(i?.creatureId,i?.roomId)});reg({name:'set_room_initiative',title:'Установить инициативу',description:'Устанавливает инициативу существу только в выбранной комнате.',inputSchema:{type:'object',properties:{creatureId:{type:'string'},roomId:{type:'string'},initiative:{type:'integer',minimum:-99,maximum:999}},required:['creatureId','roomId','initiative'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>window.archiveActions.setInitiative(i?.creatureId,i?.roomId,i?.initiative)})}
    history.replaceState({...(history.state||{}),archiveView:'home'},'');render();initializeAuth();registerAgentTools();
    if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'}).then(registration=>registration.update()).catch(()=>{}));
