const SYNCED_USER_KEY='initiative-cloud-user-v1',CLOUD_BASE_DB='initiative-cloud-sync-v1';
const SUPABASE_URL='https://bdozzhlmuaswqeyawzdr.supabase.co',SUPABASE_PUBLISHABLE_KEY='sb_publishable_7TKD0bDzOpr2_Q8sBz8HSw_jiD_FMyo';
const authClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})||null;

let authSession=null,authBusy=false,cloudReady=false,cloudUserId=null,cloudSyncState='local',cloudSaveTimer=null,cloudSaving=false,cloudSaveQueued=false,cloudSavePromise=null,cloudSyncToken=0,cloudBaseState=null,cloudBaseSettings=null,cloudVersion=null,cloudPendingChanges=false,networkOnline=navigator.onLine!==false;
    function cloudSettings(){return{accent:accentTheme,font:displayFont,boldSections:boldAsSection,density:interfaceDensity,combatTracking:combatTrackingEnabled,bestiaryAdvancedSearch,alternativeCreate:alternativeCreateEnabled,journal:journalEnabled,journalSearch:journalSearchEnabled,journalSections:journalSectionsEnabled,journalBoldSections,bonusHp:bonusHpEnabled,bonusHpContrast,bonusHpColor,tokenColors:tokenatorFavoriteColors}}
    function syncedUserId(){try{return localStorage.getItem(SYNCED_USER_KEY)||''}catch(_){return''}}
    function markSyncedUser(userId){try{userId?localStorage.setItem(SYNCED_USER_KEY,userId):localStorage.removeItem(SYNCED_USER_KEY)}catch(_){}}
    function archiveHasContent(archive){const library=archive?.library;return Boolean(archive?.rooms?.length||archive?.bestiary?.length||archive?.tags?.length||library?.syncTags||library?.tags?.length||library?.artifacts?.length||library?.conditions?.length)}
    function cloneJson(value){return value===undefined?undefined:JSON.parse(JSON.stringify(value))}
    function plainObject(value){return Boolean(value)&&typeof value==='object'&&!Array.isArray(value)}
    function sameJson(a,b){if(Object.is(a,b))return true;if(Array.isArray(a)||Array.isArray(b))return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((value,index)=>sameJson(value,b[index]));if(plainObject(a)||plainObject(b)){if(!plainObject(a)||!plainObject(b))return false;const aKeys=Object.keys(a),bKeys=Object.keys(b);return aKeys.length===bKeys.length&&aKeys.every(key=>Object.prototype.hasOwnProperty.call(b,key)&&sameJson(a[key],b[key]))}return false}
    function mergeSyncValue(base,local,remote,stats){
      if(sameJson(local,remote))return cloneJson(local);
      if(sameJson(local,base))return cloneJson(remote);
      if(sameJson(remote,base))return cloneJson(local);
      if(local===undefined){if(remote===undefined||sameJson(remote,base))return undefined;stats.conflicts++;return cloneJson(remote)}
      if(remote===undefined){if(sameJson(local,base))return undefined;stats.conflicts++;return cloneJson(local)}
      if(Array.isArray(local)&&Array.isArray(remote)){
        const idArrays=[base,local,remote].filter(Array.isArray).every(list=>list.every(item=>plainObject(item)&&item.id!=null));
        if(idArrays){const baseMap=new Map((base||[]).map(item=>[String(item.id),item])),localMap=new Map(local.map(item=>[String(item.id),item])),remoteMap=new Map(remote.map(item=>[String(item.id),item])),order=[];[local,remote,base||[]].forEach(list=>list.forEach(item=>{const id=String(item.id);if(!order.includes(id))order.push(id)}));return order.map(id=>mergeSyncValue(baseMap.get(id),localMap.get(id),remoteMap.get(id),stats)).filter(value=>value!==undefined)}
        const baseSet=new Set(Array.isArray(base)?base.map(JSON.stringify):[]),localSet=new Set(local.map(JSON.stringify)),remoteSet=new Set(remote.map(JSON.stringify)),result=[];[...local,...remote].forEach(item=>{const key=JSON.stringify(item),survives=!baseSet.has(key)||(localSet.has(key)&&remoteSet.has(key));if(survives&&!result.some(value=>sameJson(value,item)))result.push(cloneJson(item))});return result
      }
      if(plainObject(local)&&plainObject(remote)){const result={};new Set([...Object.keys(plainObject(base)?base:{}),...Object.keys(local),...Object.keys(remote)]).forEach(key=>{const value=mergeSyncValue(plainObject(base)?base[key]:undefined,local[key],remote[key],stats);if(value!==undefined)result[key]=value});return result}
      stats.conflicts++;return cloneJson(local)
    }
    function mergeConcurrentData(baseState,localState,remoteState,baseSettings={},localSettings={},remoteSettings={}){const stats={conflicts:0},mergedState=mergeSyncValue(baseState,localState,remoteState,stats),settings=mergeSyncValue(baseSettings,localSettings,remoteSettings,stats);return{state:normalize(mergedState||{rooms:[],bestiary:[],tags:[]}),settings:settings||{},conflicts:stats.conflicts}}
    function openCloudBaseDb(){return new Promise(resolve=>{if(!window.indexedDB){resolve(null);return}const request=indexedDB.open(CLOUD_BASE_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('bases',{keyPath:'userId'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(null)})}
    async function loadCloudBase(userId){const db=await openCloudBaseDb();if(!db)return null;return new Promise(resolve=>{const transaction=db.transaction('bases','readonly'),request=transaction.objectStore('bases').get(userId);request.onsuccess=()=>{const saved=request.result;resolve(saved?.state&&Array.isArray(saved.state.rooms)&&Array.isArray(saved.state.bestiary)?saved:null)};request.onerror=()=>resolve(null);transaction.oncomplete=()=>db.close();transaction.onerror=()=>{db.close();resolve(null)}})}
    async function storeCloudBase(userId,version,archive,settings){const db=await openCloudBaseDb();if(!db)return;await new Promise(resolve=>{const transaction=db.transaction('bases','readwrite');transaction.objectStore('bases').put({userId,version,state:archive,settings});transaction.oncomplete=resolve;transaction.onerror=resolve});db.close()}
    async function clearCloudBase(){const db=await openCloudBaseDb();if(!db)return;await new Promise(resolve=>{const transaction=db.transaction('bases','readwrite');transaction.objectStore('bases').clear();transaction.oncomplete=resolve;transaction.onerror=resolve});db.close()}
    function setCloudBase(userId,version,archive,settings){cloudVersion=version||null;cloudBaseState=cloneJson(archive);cloudBaseSettings=cloneJson(settings||{});storeCloudBase(userId,cloudVersion,cloudBaseState,cloudBaseSettings).catch(()=>{})}
    function updateCloudStatus(){const line=el('auth-sync-line'),label=el('auth-sync-label'),retry=el('auth-sync-retry'),top=el('save-status'),topLabel=el('save-status-label'),signedIn=Boolean(authSession?.user),effectiveState=signedIn&&!networkOnline?'offline':cloudSyncState,states={local:'Данные хранятся только на этом устройстве',loading:'Загружаем данные аккаунта…',saving:'Сохраняем изменения…',synced:'Данные синхронизированы',offline:'Офлайн — изменения сохранены на устройстве',error:'Не удалось синхронизировать данные'};if(line&&label){line.dataset.state=effectiveState;label.textContent=states[effectiveState]||states.local;if(retry)retry.hidden=effectiveState!=='error'}if(!top||!topLabel)return;let status='saved',text='Сохранено',title='Данные сохранены на этом устройстве';if(localSaveFailed){status='error';text='Ошибка сохранения';title='Не удалось сохранить данные на этом устройстве'}else if(localSavePending){status='saving';text='Сохранение…';title='Сохраняем данные на этом устройстве'}else if(signedIn){if(effectiveState==='loading'||effectiveState==='saving'){status='syncing';text='Синхронизация…';title=states[effectiveState]}else if(effectiveState==='offline'){status='offline';text='Офлайн';title=states.offline}else if(effectiveState==='error'){status='error';text='Ошибка синхронизации';title=states.error}else if(effectiveState==='synced'){status='saved';text='Сохранено';title=states.synced}else if(cloudPendingChanges){status='pending';text='Не синхронизировано';title='Изменения сохранены на устройстве и ожидают синхронизации'}}top.dataset.state=status;topLabel.textContent=text;top.title=title;top.setAttribute('aria-label',title)}
    function applyCloudSettings(settings){if(!settings||typeof settings!=='object')return;const cloudFont=settings.font==='made-winter'?'old-town':settings.font;applyAccent(ACCENT_THEMES[settings.accent]?settings.accent:accentTheme,false);applyDisplayFont(DISPLAY_FONTS[cloudFont]?cloudFont:displayFont,false);applyBoldSections(typeof settings.boldSections==='boolean'?settings.boldSections:boldAsSection,false);applyInterfaceDensity(Number.isInteger(Number(settings.density))?Number(settings.density):interfaceDensity,false);applyCombatTracking(typeof settings.combatTracking==='boolean'?settings.combatTracking:combatTrackingEnabled,false);applyBestiaryAdvancedSearch(typeof settings.bestiaryAdvancedSearch==='boolean'?settings.bestiaryAdvancedSearch:bestiaryAdvancedSearch,false);applyAlternativeCreate(typeof settings.alternativeCreate==='boolean'?settings.alternativeCreate:alternativeCreateEnabled,false);applyJournalEnabled(typeof settings.journal==='boolean'?settings.journal:journalEnabled,false);applyJournalSearch(typeof settings.journalSearch==='boolean'?settings.journalSearch:journalSearchEnabled,false);applyJournalSections(typeof settings.journalSections==='boolean'?settings.journalSections:journalSectionsEnabled,false);applyJournalBoldSections(typeof settings.journalBoldSections==='boolean'?settings.journalBoldSections:journalBoldSections,false);applyBonusHpEnabled(typeof settings.bonusHp==='boolean'?settings.bonusHp:bonusHpEnabled,false);applyBonusHpStyle(typeof settings.bonusHpContrast==='boolean'?settings.bonusHpContrast:bonusHpContrast,ACCENT_THEMES[settings.bonusHpColor]?settings.bonusHpColor:bonusHpColor,false);tokenatorFavoriteColors=Array.isArray(settings.tokenColors)?[...new Set(settings.tokenColors.filter(validTokenColor))].slice(0,12):tokenatorFavoriteColors;try{localStorage.setItem(ACCENT_KEY,accentTheme);localStorage.setItem(FONT_KEY,displayFont);localStorage.setItem(BOLD_SECTIONS_KEY,String(boldAsSection));localStorage.setItem(DENSITY_KEY,String(interfaceDensity));localStorage.setItem(COMBAT_TRACKING_KEY,String(combatTrackingEnabled));localStorage.setItem(BESTIARY_ADVANCED_SEARCH_KEY,String(bestiaryAdvancedSearch));localStorage.setItem(ALTERNATIVE_CREATE_KEY,String(alternativeCreateEnabled));localStorage.setItem(JOURNAL_KEY,String(journalEnabled));localStorage.setItem(JOURNAL_SEARCH_KEY,String(journalSearchEnabled));localStorage.setItem(JOURNAL_SECTIONS_KEY,String(journalSectionsEnabled));localStorage.setItem(JOURNAL_BOLD_SECTIONS_KEY,String(journalBoldSections));localStorage.setItem(BONUS_HP_KEY,String(bonusHpEnabled));localStorage.setItem(BONUS_HP_CONTRAST_KEY,String(bonusHpContrast));localStorage.setItem(BONUS_HP_COLOR_KEY,bonusHpColor);localStorage.setItem(TOKEN_COLORS_KEY,JSON.stringify(tokenatorFavoriteColors))}catch(_){}}
    function scheduleCloudSave(){if(!authSession?.user||cloudUserId!==authSession.user.id)return;cloudPendingChanges=true;clearTimeout(cloudSaveTimer);if(!networkOnline){cloudSyncState='offline';updateCloudStatus();return}if(!cloudReady){updateCloudStatus();return}cloudSyncState='saving';updateCloudStatus();cloudSaveTimer=setTimeout(saveCloudNow,1200)}
    function nextCloudVersion(expected){const now=Date.now(),previous=Date.parse(expected||'');return new Date(Number.isFinite(previous)&&previous>=now?previous+1:now).toISOString()}
    async function fetchCloudArchive(userId){return authClient.from('user_archives').select('data,settings,updated_at').eq('user_id',userId).maybeSingle()}
    async function writeCloudSnapshot(userId,archive,settings,expectedVersion){const updatedAt=nextCloudVersion(expectedVersion),payload={user_id:userId,data:archive,settings,updated_at:updatedAt};if(expectedVersion){const {data,error}=await authClient.from('user_archives').update(payload).eq('user_id',userId).eq('updated_at',expectedVersion).select('updated_at').maybeSingle();return{data,error,conflict:!error&&!data}}const {data,error}=await authClient.from('user_archives').insert(payload).select('updated_at').single();return{data,error:error?.code==='23505'?null:error,conflict:error?.code==='23505'}}
    async function performCloudSave(userId,startState,startSettings,startMutationVersion){let workingState=cloneJson(startState),workingSettings=cloneJson(startSettings),baseState=cloneJson(cloudBaseState)||{rooms:[],bestiary:[],tags:[]},baseSettings=cloneJson(cloudBaseSettings)||{},expectedVersion=cloudVersion,mergedRemote=false,conflicts=0;for(let attempt=0;attempt<4;attempt++){const written=await writeCloudSnapshot(userId,workingState,workingSettings,expectedVersion);if(written.error)return{ok:false,error:written.error};if(!written.conflict){setCloudBase(userId,written.data.updated_at,workingState,workingSettings);if(mergedRemote){if(localMutationVersion===startMutationVersion){state=normalize(cloneJson(workingState));applyCloudSettings(workingSettings);render()}else{const carried=mergeConcurrentData(startState,state,workingState,startSettings,cloudSettings(),workingSettings);state=carried.state;applyCloudSettings(carried.settings);conflicts+=carried.conflicts;cloudSaveQueued=true}scheduleLocalSave()}if(localMutationVersion!==startMutationVersion)cloudSaveQueued=true;return{ok:true,mergedRemote,conflicts}}const latest=await fetchCloudArchive(userId);if(latest.error)return{ok:false,error:latest.error};const remoteState=latest.data?.data&&Array.isArray(latest.data.data.rooms)&&Array.isArray(latest.data.data.bestiary)?normalize(cloneJson(latest.data.data)):{rooms:[],bestiary:[],tags:[]},remoteSettings=latest.data?.settings||{},merged=mergeConcurrentData(baseState,workingState,remoteState,baseSettings,workingSettings,remoteSettings);workingState=merged.state;workingSettings=merged.settings;conflicts+=merged.conflicts;mergedRemote=true;baseState=cloneJson(remoteState);baseSettings=cloneJson(remoteSettings);expectedVersion=latest.data?.updated_at||null}return{ok:false,error:new Error('Слишком много одновременных изменений')}}
    async function saveCloudNow(){if(!cloudReady||!authSession?.user||cloudUserId!==authSession.user.id)return false;clearTimeout(cloudSaveTimer);persistLocalState();if(!networkOnline){cloudPendingChanges=true;cloudSyncState='offline';updateCloudStatus();return false}if(cloudSaving){cloudSaveQueued=true;cloudPendingChanges=true;return cloudSavePromise||false}const userId=authSession.user.id,startState=cloneJson(state),startSettings=cloudSettings(),startMutationVersion=localMutationVersion;cloudSaving=true;cloudSaveQueued=false;cloudSyncState='saving';updateCloudStatus();cloudSavePromise=performCloudSave(userId,startState,startSettings,startMutationVersion);const result=await cloudSavePromise;cloudSavePromise=null;cloudSaving=false;if(cloudUserId!==userId)return false;if(!result.ok){cloudPendingChanges=true;cloudSyncState=networkOnline?'error':'offline';updateCloudStatus();if(networkOnline)showToast('Не удалось сохранить данные аккаунта');return false}markSyncedUser(userId);if(result.mergedRemote)showToast(result.conflicts?'Изменения объединены; при совпадении сохранён вариант этого устройства':'Изменения с другого устройства объединены');if(cloudSaveQueued){cloudPendingChanges=true;scheduleCloudSave()}else{cloudPendingChanges=false;cloudSyncState='synced';updateCloudStatus()}return true}
    async function flushCloudSave(){clearTimeout(cloudSaveTimer);persistLocalState();if(cloudSaving&&cloudSavePromise){const result=await cloudSavePromise;if(!result?.ok)return false;if(!cloudSaveQueued)return true}clearTimeout(cloudSaveTimer);return saveCloudNow()}
    async function connectCloudSession(session){const userId=session?.user?.id;if(!userId)return;if(cloudUserId===userId&&(cloudReady||cloudSyncState==='loading'))return;const token=++cloudSyncToken,localState=cloneJson(state),localSettings=cloudSettings(),wasSynced=syncedUserId()===userId;cloudUserId=userId;cloudReady=false;if(!networkOnline){cloudSyncState='offline';updateCloudStatus();return}cloudSyncState='loading';updateCloudStatus();const [cloudResult,savedBase]=await Promise.all([fetchCloudArchive(userId),loadCloudBase(userId)]),{data,error}=cloudResult;if(token!==cloudSyncToken||cloudUserId!==userId)return;if(error){cloudSyncState=networkOnline?'error':'offline';updateCloudStatus();if(networkOnline)showToast('Не удалось загрузить данные аккаунта');return}if(data?.data&&Array.isArray(data.data.rooms)&&Array.isArray(data.data.bestiary)){const remoteSchemaVersion=archiveSchemaVersion(data.data),remoteConditionPresetSystemVersion=Number(data.data.library?.conditionPresetSystemVersion)||0,remoteState=normalize(cloneJson(data.data)),remoteSettings=data.settings||{};setCloudBase(userId,data.updated_at,remoteState,remoteSettings);let merged={state:remoteState,settings:remoteSettings,conflicts:0};if(savedBase)merged=mergeConcurrentData(savedBase.state,localState,remoteState,savedBase.settings||{},localSettings,remoteSettings);else if(wasSynced||archiveHasContent(localState)||cloudPendingChanges)merged=mergeConcurrentData({rooms:[],bestiary:[],tags:[]},localState,remoteState,{},localSettings,remoteSettings);state=merged.state;applyCloudSettings(merged.settings);scheduleLocalSave();persistLocalState();cloudReady=true;const needsSave=remoteSchemaVersion!==CURRENT_SCHEMA_VERSION||remoteConditionPresetSystemVersion<CONDITION_PRESET_SYSTEM_VERSION||cloudPendingChanges||!sameJson(state,remoteState)||!sameJson(cloudSettings(),remoteSettings);if(needsSave){await saveCloudNow();if(networkOnline)showToast(merged.conflicts?'Данные устройств объединены; совпавшие поля оставлены с этого устройства':'Данные устройств объединены')}else{cloudPendingChanges=false;markSyncedUser(userId);cloudSyncState='synced';updateCloudStatus()}render();return}setCloudBase(userId,null,{rooms:[],bestiary:[],tags:[]},{});cloudReady=true;cloudPendingChanges=true;await saveCloudNow();if(networkOnline)showToast('Данные этого устройства сохранены в аккаунте')}
    function disconnectCloudSession(){cloudSyncToken++;cloudReady=false;cloudUserId=null;cloudSyncState='local';cloudSaveQueued=false;cloudPendingChanges=false;cloudBaseState=null;cloudBaseSettings=null;cloudVersion=null;clearTimeout(cloudSaveTimer);updateCloudStatus()}
    function clearAccountArchive(){state=normalize({rooms:[],bestiary:[],tags:[]});view={name:'home',roomId:null};markSyncedUser('');clearCloudBase().catch(()=>{});applyAccent('gold',false);applyDisplayFont('georgia',false);applyBoldSections(false,false);applyCombatTracking(false,false);applyJournalEnabled(false,false);applyJournalSearch(false,false);applyJournalSections(false,false);applyJournalBoldSections(false,false);applyBonusHpEnabled(false,false);try{localStorage.removeItem(KEY);localStorage.removeItem(ACCENT_KEY);localStorage.removeItem(FONT_KEY);localStorage.removeItem(BOLD_SECTIONS_KEY);localStorage.removeItem(COMBAT_TRACKING_KEY);localStorage.removeItem(JOURNAL_KEY);localStorage.removeItem(JOURNAL_SEARCH_KEY);localStorage.removeItem(JOURNAL_SECTIONS_KEY);localStorage.removeItem(JOURNAL_BOLD_SECTIONS_KEY);localStorage.removeItem(BONUS_HP_KEY)}catch(_){}render()}
    function handleAuthSession(session){const nextUserId=session?.user?.id||'',localOwner=syncedUserId();if(nextUserId&&localOwner&&localOwner!==nextUserId)clearAccountArchive();authSession=session;updateAuthButton();if(session?.user)connectCloudSession(session);else disconnectCloudSession();if(el('auth-dialog').open)renderAuthDialog()}
    async function retryCloudSync(){if(!authSession?.user)return false;if(!networkOnline){cloudSyncState='offline';updateCloudStatus();return false}if(cloudReady&&cloudUserId===authSession.user.id)return saveCloudNow();return connectCloudSession(authSession)}
    function authMessage(message,type=''){const status=el('auth-status');status.textContent=message||'';status.className=`auth-status${type?` ${type}`:''}`}
    function authErrorText(error){const text=String(error?.message||'Не удалось выполнить вход. Попробуйте ещё раз.');if(/rate limit/i.test(text))return'Слишком много запросов. Подождите минуту и попробуйте ещё раз.';if(/expired|invalid.*token|token.*invalid/i.test(text))return'Ссылка недействительна или уже истекла. Запросите новое письмо.';if(/email.*invalid|invalid.*email/i.test(text))return'Проверьте, правильно ли указана почта.';return text}
    function setAuthBusy(busy){authBusy=busy;['auth-google','auth-signout'].forEach(id=>{const button=el(id);if(button)button.disabled=busy})}
    function updateAuthButton(){const user=authSession?.user,email=user?.email||'',button=el('account-button'),avatar=el('account-avatar'),avatarUrl=user?.user_metadata?.avatar_url||user?.user_metadata?.picture||'';el('account-label').textContent=email||'Войти';avatar.replaceChildren();avatar.classList.toggle('has-image',Boolean(avatarUrl));if(avatarUrl){const image=document.createElement('img');image.src=avatarUrl;image.alt='';image.referrerPolicy='no-referrer';image.addEventListener('error',()=>{avatar.classList.remove('has-image');avatar.textContent='●'},{once:true});avatar.append(image)}else avatar.textContent='●';button.setAttribute('aria-label',email?`Аккаунт: ${email}`:'Войти в аккаунт');button.title=email||'Войти через Google'}
    function renderAuthDialog(){const signedIn=Boolean(authSession?.user),login=el('auth-login-view'),account=el('auth-account-view');login.hidden=signedIn;account.hidden=!signedIn;el('auth-title').textContent=signedIn?'Аккаунт':'Вход в аккаунт';if(signedIn){el('auth-account-email').textContent=authSession.user.email||'Аккаунт';updateCloudStatus()}}
    function openAuthDialog(){renderAuthDialog();authMessage('');el('auth-dialog').showModal();if(authSession&&cloudSyncState==='error')retryCloudSync();setTimeout(()=>{(authSession?el('auth-signout'):el('auth-google'))?.focus()},0)}
    async function signInWithGoogle(){if(!authClient){authMessage('Сервис входа не загрузился. Обновите страницу и попробуйте снова.','error');return}setAuthBusy(true);authMessage('Открываем вход через Google…');const {error}=await authClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}${location.pathname}`}});if(error){setAuthBusy(false);authMessage(authErrorText(error),'error')}}
    async function signOutAccount(){if(!authClient)return;setAuthBusy(true);const archiveWasSaved=cloudReady?await flushCloudSave():false;if(cloudReady&&!archiveWasSaved){setAuthBusy(false);showToast('Сначала дождитесь сохранения данных');return}const {error}=await authClient.auth.signOut();setAuthBusy(false);if(error){showToast(authErrorText(error));return}authSession=null;disconnectCloudSession();if(archiveWasSaved)clearAccountArchive();el('auth-dialog').close();updateAuthButton();showToast('Вы вышли из аккаунта')}
    function initializeAuth(){updateAuthButton();updateCloudStatus();if(!authClient)return;authClient.auth.onAuthStateChange((_event,session)=>setTimeout(()=>handleAuthSession(session),0));authClient.auth.getSession().then(({data})=>handleAuthSession(data.session)).catch(()=>{cloudSyncState=networkOnline?'error':'offline';updateCloudStatus()})}
