const CURRENT_SCHEMA_VERSION=1;

const DND_CONDITIONS_VERSION=2;
const DND_STANDARD_CONDITIONS=[
  {id:'dnd-condition-blinded',name:'Ослеплённый',description:'Не видит; свои атаки — с Помехой, атаки по нему — с Преимуществом.',details:'- **Зрение:** не видит и автоматически проваливает проверки характеристик, требующие зрения.\n- **Атаки:** броски атаки существа совершаются с Помехой; броски атаки по нему — с Преимуществом.',builtin:true},
  {id:'dnd-condition-charmed',name:'Очарованный',description:'Не может вредить очаровавшему; очаровавший получает Преимущество в социальных проверках.',details:'- **Запрет вредить:** нельзя атаковать очаровавшее существо или выбирать его целью наносящих урон способностей и магических эффектов.\n- **Социальное влияние:** очаровавший совершает с Преимуществом проверки характеристик при социальном взаимодействии с целью.',builtin:true},
  {id:'dnd-condition-deafened',name:'Оглохший',description:'Не слышит и автоматически проваливает проверки, требующие слуха.',details:'- **Слух:** существо не слышит.\n- **Проверки:** автоматически проваливает проверки характеристик, для которых необходим слух.',builtin:true},
  {id:'dnd-condition-exhaustion',name:'Истощение',description:'Уровни 1–6: −2 к Тестам d20 и −5 футов Скорости за каждый уровень; 6-й уровень — смерть.',details:'- **Накопление:** Истощение складывается само с собой; каждый новый эффект повышает уровень на 1.\n- **Тесты d20:** результат уменьшается на 2 × уровень Истощения.\n- **Скорость:** уменьшается на 5 футов × уровень Истощения.\n- **6-й уровень:** существо умирает.\n- **Долгий отдых:** снижает уровень Истощения на 1; на уровне 0 состояние заканчивается.',builtin:true},
  {id:'dnd-condition-frightened',name:'Испуганный',description:'Пока источник страха виден — Помеха к атакам и проверкам; нельзя добровольно приближаться к нему.',details:'- **Источник в поле зрения:** проверки характеристик и броски атаки совершаются с Помехой.\n- **Перемещение:** нельзя добровольно перемещаться ближе к источнику страха.',builtin:true},
  {id:'dnd-condition-grappled',name:'Схваченный',description:'Скорость 0; хуже атакует не захватчика; захватчик может тащить или нести цель.',details:'- **Скорость:** равна 0 и не может быть увеличена.\n- **Атаки:** броски атаки по целям, кроме захватившего существа, совершаются с Помехой.\n- **Перемещение захватчиком:** захватившее существо может тащить или нести цель; каждый фут такого перемещения обычно стоит дополнительный фут движения. Исключение — цель Крошечная или минимум на два размера меньше захватчика.',builtin:true},
  {id:'dnd-condition-incapacitated',name:'Недееспособный',description:'Нет действий, Бонусных действий и Реакций; нельзя концентрироваться и говорить; Помеха к Инициативе.',details:'- **Действия:** нельзя совершать действия, Бонусные действия и Реакции.\n- **Концентрация:** нельзя поддерживать Концентрацию.\n- **Речь:** нельзя говорить.\n- **Инициатива:** бросок Инициативы совершается с Помехой.',builtin:true},
  {id:'dnd-condition-invisible',name:'Невидимый',description:'Преимущество к Инициативе и атакам; атаки по нему — с Помехой; эффекты, требующие видимой цели, обычно не работают.',details:'- **Инициатива:** бросок совершается с Преимуществом.\n- **Скрытость:** эффекты, которым нужно видеть цель, не могут воздействовать на существо, если создатель эффекта не способен его видеть. Носимое и несомое снаряжение также скрыто.\n- **Атаки:** атаки существа совершаются с Преимуществом, а атаки по нему — с Помехой, если противник не способен его видеть.',builtin:true},
  {id:'dnd-condition-paralyzed',name:'Парализованный',description:'Недееспособен, Скорость 0, проваливает спасброски Силы и Ловкости; попадания вблизи становятся критическими.',details:'- **Недееспособность:** также получает состояние Недееспособный.\n- **Скорость:** равна 0 и не может быть увеличена.\n- **Спасброски:** автоматически проваливает спасброски Силы и Ловкости.\n- **Атаки по цели:** совершаются с Преимуществом.\n- **Критические попадания:** любое попадание атакой в пределах 5 футов считается Критическим попаданием.',builtin:true},
  {id:'dnd-condition-petrified',name:'Окаменевший',description:'Недееспособен и неподвижен; получает Сопротивление всему урону и Иммунитет к Отравлению.',details:'- **Превращение:** существо и все его немагические носимые/несомые предметы становятся твёрдой неодушевлённой материей; вес увеличивается в 10 раз, старение прекращается.\n- **Недееспособность:** также получает состояние Недееспособный.\n- **Скорость:** равна 0 и не может быть увеличена.\n- **Спасброски:** автоматически проваливает спасброски Силы и Ловкости.\n- **Атаки по цели:** совершаются с Преимуществом.\n- **Защита:** Сопротивление всему урону и Иммунитет к состоянию Отравленный.',builtin:true},
  {id:'dnd-condition-poisoned',name:'Отравленный',description:'Броски атаки и проверки характеристик совершаются с Помехой.',details:'- **Атаки:** броски атаки совершаются с Помехой.\n- **Проверки:** проверки характеристик совершаются с Помехой.',builtin:true},
  {id:'dnd-condition-prone',name:'Опрокинутый',description:'Ползёт или тратит половину Скорости, чтобы встать; свои атаки — с Помехой.',details:'- **Перемещение:** можно только ползти либо потратить перемещение, равное половине Скорости, чтобы встать. При Скорости 0 встать нельзя.\n- **Свои атаки:** броски атаки совершаются с Помехой.\n- **Атаки по цели:** с Преимуществом, если атакующий в пределах 5 футов; с Помехой, если дальше 5 футов.',builtin:true},
  {id:'dnd-condition-restrained',name:'Опутанный',description:'Скорость 0; свои атаки и спасброски Ловкости — с Помехой; атаки по нему — с Преимуществом.',details:'- **Скорость:** равна 0 и не может быть увеличена.\n- **Атаки:** броски атаки существа совершаются с Помехой; броски атаки по нему — с Преимуществом.\n- **Спасброски Ловкости:** совершаются с Помехой.',builtin:true},
  {id:'dnd-condition-stunned',name:'Ошеломлённый',description:'Недееспособен, автоматически проваливает спасброски Силы и Ловкости; атаки по нему — с Преимуществом.',details:'- **Недееспособность:** также получает состояние Недееспособный.\n- **Спасброски:** автоматически проваливает спасброски Силы и Ловкости.\n- **Атаки по цели:** совершаются с Преимуществом.',builtin:true},
  {id:'dnd-condition-unconscious',name:'Бессознательный',description:'Недееспособен и Опрокинут, Скорость 0; попадания вблизи становятся критическими.',details:'- **Бездеятельность:** получает состояния Недееспособный и Опрокинутый и роняет всё, что держит. После окончания Бессознательности остаётся Опрокинутым.\n- **Скорость:** равна 0 и не может быть увеличена.\n- **Атаки по цели:** совершаются с Преимуществом.\n- **Спасброски:** автоматически проваливает спасброски Силы и Ловкости.\n- **Критические попадания:** любое попадание атакой в пределах 5 футов считается Критическим попаданием.\n- **Осознание:** не осознаёт происходящее вокруг.',builtin:true}
];

function archiveSchemaVersion(data){if(!data||typeof data!=='object'||Array.isArray(data))return 0;const version=Number(data.schemaVersion);return Number.isInteger(version)&&version>=0?version:0}
    function migrateArchive(data){
      if(!data||typeof data!=='object'||Array.isArray(data))data={};
      let version=archiveSchemaVersion(data);
      if(version>CURRENT_SCHEMA_VERSION)throw new Error(`Версия архива ${version} новее поддерживаемой ${CURRENT_SCHEMA_VERSION}`);
      while(version<CURRENT_SCHEMA_VERSION){
        if(version===0){if(!Array.isArray(data.rooms))data.rooms=[];if(!Array.isArray(data.bestiary))data.bestiary=[];if(!Array.isArray(data.tags))data.tags=[];data.schemaVersion=1;version=1;continue}
        throw new Error(`Нет миграции архива v${version} -> v${version+1}`);
      }
      data.schemaVersion=CURRENT_SCHEMA_VERSION;
      return data;
    }
function normalize(data){
  data=migrateArchive(data);
  const normalizeCreature=c=>{if(c.description==null)c.description='';if(c.hp==null)c.hp='';if(c.ac==null)c.ac='';if(c.characteristics==null)c.characteristics='';if(c.abilities==null)c.abilities='';if(c.notes==null)c.notes='';if(!Array.isArray(c.tagIds))c.tagIds=[];return c};
  const normalizeLibraryItem=item=>{if(!item||typeof item!=='object')item={};if(!item.id)item.id=makeId();item.name=String(item.name||'Без названия').slice(0,80);item.description=String(item.description||'').slice(0,240);item.details=String(item.details||'').slice(0,6000);if(!Array.isArray(item.tagIds))item.tagIds=[];item.builtin=Boolean(item.builtin);return item};
  if(!Array.isArray(data.tags))data.tags=[];
  data.tags=data.tags.map(t=>({id:t.id||makeId(),name:String(t.name||'Тег').slice(0,30),color:validTagColor(t.color)}));
  data.bestiary.forEach(normalizeCreature);
  data.rooms.forEach(r=>{if(r.journal==null)r.journal='';if(!r.initiatives||typeof r.initiatives!=='object')r.initiatives={};if(!r.combatNotes||typeof r.combatNotes!=='object')r.combatNotes={};if(!r.currentHp||typeof r.currentHp!=='object')r.currentHp={};if(!r.bonusHp||typeof r.bonusHp!=='object')r.bonusHp={};if(!Array.isArray(r.entries)){const used=new Set;r.entries=(Array.isArray(r.creatureIds)?r.creatureIds:[]).map(creatureId=>{let id=creatureId;if(used.has(id)){id=makeId();if(Object.prototype.hasOwnProperty.call(r.initiatives,creatureId))r.initiatives[id]=r.initiatives[creatureId];if(Object.prototype.hasOwnProperty.call(r.combatNotes,creatureId))r.combatNotes[id]=r.combatNotes[creatureId];if(Object.prototype.hasOwnProperty.call(r.currentHp,creatureId))r.currentHp[id]=r.currentHp[creatureId];if(Object.prototype.hasOwnProperty.call(r.bonusHp,creatureId))r.bonusHp[id]=r.bonusHp[creatureId]}used.add(id);return{id,creatureId}})}r.entries=r.entries.map(entry=>{const normalized={id:entry.id||makeId(),creatureId:entry.creatureId||null};if(!normalized.creatureId)normalized.npc=normalizeCreature(entry.npc&&typeof entry.npc==='object'?entry.npc:{name:'',description:'',hp:'',ac:'',characteristics:'',abilities:'',notes:'',tagIds:[]});return normalized});delete r.creatureIds;if(!r.combat||typeof r.combat!=='object')r.combat={active:false,round:1,turnCreatureId:null};r.combat.active=Boolean(r.combat.active);r.combat.round=Math.max(1,Math.trunc(Number(r.combat.round)||1));if(r.combat.turnCreatureId==null)r.combat.turnCreatureId=null});
  const hadLibrary=Boolean(data.library&&typeof data.library==='object'&&!Array.isArray(data.library));
  if(!hadLibrary)data.library={syncTags:false,tags:[],conditions:DND_STANDARD_CONDITIONS.map(item=>({...item,tagIds:[]})),artifacts:[]};
  if(typeof data.library.syncTags!=='boolean')data.library.syncTags=false;
  if(!Array.isArray(data.library.tags))data.library.tags=[];
  data.library.tags=data.library.tags.map(t=>({id:t.id||makeId(),name:String(t.name||'Тег').slice(0,30),color:validTagColor(t.color)}));
  if(!Array.isArray(data.library.conditions))data.library.conditions=DND_STANDARD_CONDITIONS.map(item=>({...item,tagIds:[]}));
  if(!Array.isArray(data.library.artifacts))data.library.artifacts=[];
  data.library.conditions=data.library.conditions.map(normalizeLibraryItem);
  data.library.artifacts=data.library.artifacts.map(normalizeLibraryItem);
  return data
}
