const CURRENT_SCHEMA_VERSION=1;

const CONDITION_PRESET_SYSTEM_VERSION=3;
const DND_CONDITIONS_5E24=[
  {id:'dnd-condition-unconscious',name:'Бессознательный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Бессознательный, на вас действуют следующие эффекты:\n\n**Бездеятельность.** У вас есть состояния Недееспособный и Опрокинутый, и вы роняете всё, что держите. Когда ваше состояние Бессознательный заканчивается, вы остаётесь Опрокинутым.\n\n**Скорость 0.** Ваша Скорость равна 0 и не может быть увеличена.\n\n**Влияние на атаки.** Броски атаки по вам совершаются с Преимуществом.\n\n**Влияние на спасброски.** Вы автоматически проваливаете спасброски Силы и Ловкости.\n\n**Автоматические критические попадания.** Все броски атаки, попадающие по вам, считаются Критическими попаданиями, если атакующий находится в пределах 5 футов от вас.\n\n**Неосознанность.** Вы не осознаете своё окружение.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-frightened',name:'Испуганный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Испуганный, на вас действуют следующие эффекты:\n\n**Влияние на атаки и проверки характеристик.** Пока источник страха на линии вашего обзора, вы совершаете с Помехой проверки характеристик и броски атаки.\n\n**Не можете приближаться.** Вы не можете добровольно приближаться к источнику страха.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-exhaustion',name:'Истощение (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Истощения, на вас действуют следующие эффекты:\n\n**Уровни истощения.** Это состояние складывается само с собой. Каждый раз, когда вы получаете это состояние, уровень Истощения увеличивается на 1. Когда уровень Истощения становится 6, вы умираете.\n\n**Влияние на тесты к20.** Когда вы совершаете Тест к20, результат броска уменьшается на уровень Истощения, умноженный на 2.\n\n**Снижение скорости.** Ваша Скорость снижается на уровень Истощения, умноженный на 5.\n\n**Снятие уровней истощения.** Когда вы завершаете Долгий отдых, уровень Истощения снижается на 1. Когда уровень Истощения снижается до 0, состояние на вас заканчивается.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-invisible',name:'Невидимый (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Невидимый, на вас действуют следующие эффекты:\n\n**Внезапность.** Если вы совершаете бросок Инициативы с состоянием Невидимый, то делаете это с Преимуществом.\n\n**Скрытость.** На вас не может влиять никакой эффект, требующий, чтобы его цель была видна, если только создатель такого эффекта не может каким-либо образом видеть вас. Всё несомое и носимое вами снаряжение также скрывается.\n\n**Влияние на атаки.** Броски атаки по вам совершаются с Помехой, а ваши броски атаки совершаются с Преимуществом, если только существо не может каким-либо образом видеть вас.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-incapacitated',name:'Недееспособный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Недееспособный, на вас действуют следующие эффекты:\n\n**Бездействие.** Вы не можете совершать действия, Бонусные действия и Реакции.\n\n**Без концентрации.** Вы не можете Концентрироваться.\n\n**Безмолвие.** Вы не можете говорить.\n\n**Потрясение.** Если вы совершаете бросок Инициативы с состоянием Недееспособный, то делаете это с Помехой.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-deafened',name:'Оглохший (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Оглохший, на вас действует следующий эффект:\n\n**Не можете слышать.** Вы не можете слышать и автоматически проваливаете проверки характеристик, требующие слуха.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-petrified',name:'Окаменевший (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Окаменевший, на вас действуют следующие эффекты:\n\n**Неодушевлённая материя.** Вы, вместе со всеми немагическими объектами, которые вы несёте или носите, обращены в твёрдую неодушевлённую материю (обычно — в камень). Ваш вес увеличивается в десять раз, и вы перестаёте стареть.\n\n**Недееспособный.** У вас есть состояние Недееспособный.\n\n**Скорость 0.** Ваша Скорость равна 0 и не может быть увеличена.\n\n**Влияние на спасброски.** Вы автоматически проваливаете спасброски Силы и Ловкости.\n\n**Влияние на атаки.** Броски атаки по вам совершаются с Преимуществом.\n\n**Сопротивление урону.** У вас есть Сопротивление всему урону.\n\n**Иммунитет к отравлению.** У вас есть Иммунитет к состоянию Отравленный.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-prone',name:'Опрокинутый (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Опрокинутый, на вас действуют следующие эффекты:\n\n**Ограниченное перемещение.** Вы можете перемещаться только ползком, или вы можете потратить перемещение в размере, равном половине вашей Скорости (округляя вниз), чтобы подняться и таким образом окончить на себе это состояние. Вы не можете подняться, если ваша Скорость равна 0.\n\n**Влияние на атаки.** Вы совершаете с Помехой броски атаки. Броски атаки по вам совершаются с Преимуществом, если атакующий находится в пределах 5 футов от вас; броски атаки по вам совершаются с Помехой, если атакующий находится далее 5 футов от вас.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-restrained',name:'Опутанный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Опутанный, на вас действуют следующие эффекты:\n\n**Скорость 0.** Ваша Скорость равна 0 и не может быть увеличена.\n\n**Влияние на атаки.** Ваши броски атаки совершаются с Помехой, а броски атаки по вам совершаются с Преимуществом.\n\n**Влияние на спасброски.** Вы совершаете с Помехой спасброски Ловкости.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-blinded',name:'Ослеплённый (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Ослеплённый, на вас действуют следующие эффекты:\n\n**Не можете видеть.** Вы не можете видеть и автоматически проваливаете проверки характеристик, требующие зрения.\n\n**Влияние на атаки.** Ваши броски атаки совершаются с Помехой, а броски атаки по вам совершаются с Преимуществом.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-poisoned',name:'Отравленный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Отравленный, на вас действуют следующие эффекты:\n\n**Влияние на атаки и проверки характеристик.** Вы совершаете с Помехой броски атаки и проверки характеристик.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-charmed',name:'Очарованный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Очарованный, на вас действуют следующие эффекты:\n\n**Не можете вредить очаровавшему.** Вы не можете атаковать очаровавшее вас существо или нацеливать на него наносящие урон способности и магические эффекты.\n\n**Социальное преимущество.** Очаровавшее вас существо совершает с Преимуществом проверки характеристик при социальном взаимодействии с вами.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-stunned',name:'Ошеломлённый (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Ошеломлённый, на вас действуют следующие эффекты:\n\n**Недееспособность.** У вас есть состояние Недееспособный.\n\n**Влияние на спасброски.** Вы автоматически проваливаете спасброски Силы и Ловкости.\n\n**Влияние на атаки.** Броски атаки по вам совершаются с Преимуществом.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-paralyzed',name:'Парализованный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Парализованный, на вас действуют следующие эффекты:\n\n**Недееспособность.** У вас есть состояние Недееспособный.\n\n**Скорость 0.** Ваша Скорость равна 0 и не может быть увеличена.\n\n**Влияние на спасброски.** Вы автоматически проваливаете спасброски Силы и Ловкости.\n\n**Влияние на атаки.** Броски атаки по вам совершаются с Преимуществом.\n\n**Автоматические критические попадания.** Все броски атаки, попадающие по вам, считаются Критическими попаданиями, если атакующий находится в пределах 5 футов от вас.',builtin:true,preset:'5e24'},
  {id:'dnd-condition-grappled',name:'Схваченный (5е24)',description:'Состояние 5е24',details:'Пока у вас есть состояние Схваченный, на вас действуют следующие эффекты:\n\n**Скорость 0.** Ваша Скорость равна 0 и не может быть увеличена.\n\n**Влияние на атаки.** Вы совершаете с Помехой броски атаки по всем целям, кроме той, что схватила вас.\n\n**Можете быть перемещены.** Схватившее вас существо может при своём перемещении тащить или нести вас; при этом каждый фут перемещения стоит на 1 фут больше, если только вы не Крошечного размера или на два размера меньше его.',builtin:true,preset:'5e24'}
];
const DND_CONDITIONS_5E14=[
  {id:'dnd-condition-unconscious',name:'Бессознательный (5е14)',description:'Состояние 5е14',details:'- Находящееся без сознания существо недееспособно, не способно перемещаться и говорить, а также не осознаёт своё окружение.\n- Существо роняет всё, что держит, и падает ничком.\n- Существо автоматически проваливает спасброски Силы и Ловкости. Броски атаки по существу совершаются с преимуществом.\n- Любая атака, попавшая по такому существу, считается критическим попаданием, если нападающий находится в пределах 5 футов от него.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-frightened',name:'Испуганный (5е14)',description:'Состояние 5е14',details:'- Испуганное существо совершает с помехой проверки характеристик и броски атаки, пока источник его страха находится в пределах его линии обзора.\n- Существо не способно добровольно приблизиться к источнику своего страха.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-exhaustion',name:'Истощённый (5е14)',description:'Состояние 5е14',details:'Некоторые особые способности и опасности окружающей среды, такие как недоедание и длительное воздействие очень низких или высоких температур, могут стать причиной состояния, называемого истощением. Истощение делится на шесть степеней. Эффект даёт существу ту или иную степень истощения, согласно описанию.\n\n| Степень | Эффект |\n| --- | --- |\n| 1 | Помеха при проверках характеристик |\n| 2 | Скорость уменьшается вдвое |\n| 3 | Помеха при бросках атаки и спасбросках |\n| 4 | Максимум хитов уменьшается вдвое |\n| 5 | Скорость снижается до 0 |\n| 6 | Смерть |\n\nЕсли существо, уже находящееся в состоянии истощения, подвергается воздействию другого эффекта, вызывающего истощение, его текущая степень истощения повышается на значение, указанное в описании эффекта.\n\nНа существо воздействуют эффекты не только текущей степени истощения, но и более слабых степеней. Например, существо на 2 степени истощения перемещается в два раза медленнее и совершает с помехой проверки характеристик.\n\nЭффект, снимающий истощение, понижает его степень согласно описанию эффекта, вплоть до окончания действия истощения, если степень истощения существа становится ниже 1.\n\nПродолжительный отдых снижает степень истощения на 1, при условии, что существо что-нибудь съест и выпьет. Кроме того, воскрешение из мёртвых снижает уровень истощения существа на 1.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-invisible',name:'Невидимый (5е14)',description:'Состояние 5е14',details:'- Невидимое существо невозможно увидеть без помощи магии или особого чувства. С точки зрения скрытности существо считается сильно заслонённым. Местонахождение существа можно определить по шуму, который оно издаёт, или по оставленным им следам.\n- Броски атаки по невидимому существу совершаются с помехой, а его броски атаки — с преимуществом.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-incapacitated',name:'Недееспособный (5е14)',description:'Состояние 5е14',details:'- Недееспособное существо не может совершать действия и реакции.\n- Недееспособные существа автоматически проваливают проверки для сопротивления захвату или толчку.\n- Существо теряет концентрацию на заклинании, если становится недееспособным.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-deafened',name:'Оглохший (5е14)',description:'Состояние 5е14',details:'- Оглохшее существо ничего не слышит и автоматически проваливает все проверки характеристик, связанные со слухом.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-petrified',name:'Окаменевший (5е14)',description:'Состояние 5е14',details:'- Окаменевшее существо, а также все немагические предметы, которые оно несёт или носит, трансформируется в твёрдое инертное вещество (как правило, в камень). Его вес увеличивается в 10 раз, и оно перестаёт стареть.\n- Существо недееспособно, не способно двигаться и говорить, а также не осознаёт своё окружение.\n- Броски атаки по существу совершаются с преимуществом.\n- Существо автоматически проваливает спасброски Силы и Ловкости.\n- Существо получает сопротивление ко всем видам урона.\n- Существо получает иммунитет к ядам и болезням. Если яд или болезнь уже действовали на существо, их действие приостанавливается, но не исчезает.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-restrained',name:'Опутанный (5е14)',description:'Состояние 5е14',details:'- Скорость опутанного существа равна 0, и оно не получает выгоды ни от каких бонусов к скорости.\n- Броски атаки по такому существу совершаются с преимуществом, а его броски атаки — с помехой.\n- Существо совершает с помехой спасброски Ловкости.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-blinded',name:'Ослеплённый (5е14)',description:'Состояние 5е14',details:'- Ослеплённое существо ничего не видит и автоматически проваливает все проверки характеристик, связанные со зрением.\n- Броски атаки по такому существу совершаются с преимуществом, а его броски атаки совершаются с помехой.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-poisoned',name:'Отравленный (5е14)',description:'Состояние 5е14',details:'- Отравленное существо совершает с помехой броски атаки и проверки характеристик.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-charmed',name:'Очарованный (5е14)',description:'Состояние 5е14',details:'- Очарованное существо не может атаковать того, кто его очаровал, а также делать его целью умения или магического эффекта, причиняющего вред.\n- Искуситель совершает с преимуществом все проверки характеристик при социальном взаимодействии с очарованным существом.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-stunned',name:'Ошеломлённый (5е14)',description:'Состояние 5е14',details:'- Ошеломлённое существо недееспособно, не способно перемещаться и говорит, запинаясь.\n- Существо автоматически проваливает спасброски Силы и Ловкости.\n- Броски атаки по существу совершаются с преимуществом.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-paralyzed',name:'Парализованный (5е14)',description:'Состояние 5е14',details:'- Парализованное существо недееспособно и не способно перемещаться и говорить.\n- Существо автоматически проваливает спасброски Силы и Ловкости.\n- Броски атаки по парализованному существу совершаются с преимуществом.\n- Любая атака, попавшая по такому существу, считается критическим попаданием, если нападающий находится в пределах 5 футов от существа.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-prone',name:'Сбитый с ног / Лежащий ничком (5е14)',description:'Состояние 5е14',details:'- Сбитое с ног существо способно перемещаться только ползком, пока не встанет, прервав тем самым это состояние.\n- Существо совершает с помехой броски атаки.\n- Броски атаки по существу совершаются с преимуществом, если нападающий находится в пределах 5 футов от него. В противном случае броски атаки совершаются с помехой.',builtin:true,preset:'5e14'},
  {id:'dnd-condition-grappled',name:'Схваченный (5е14)',description:'Состояние 5е14',details:'- Скорость схваченного существа равна 0, и оно не получает выгоды ни от каких бонусов к скорости.\n- Состояние оканчивается, если схвативший становится недееспособным.\n- Это состояние также оканчивается, если какой-либо эффект выводит схваченное существо из зоны досягаемости того, кто его удерживает, или из зоны удерживающего эффекта. Например, когда существо отбрасывается заклинанием волна грома [thunderwave].',builtin:true,preset:'5e14'}
];
const DND_CONDITIONS_BOTH=[
  ...DND_CONDITIONS_5E14.map(item=>({...item,id:item.id+'-5e14'})),
  ...DND_CONDITIONS_5E24.map(item=>({...item,id:item.id+'-5e24'}))
];
const DND_CONDITION_PRESETS={'5e14':DND_CONDITIONS_5E14,'5e24':DND_CONDITIONS_5E24,'both':DND_CONDITIONS_BOTH};

function archiveSchemaVersion(data){if(!data||typeof data!=='object'||Array.isArray(data))return 0;const version=Number(data.schemaVersion);return Number.isInteger(version)&&version>=0?version:0}
    function migrateArchive(data){
      if(!data||typeof data!=='object'||Array.isArray(data))data={};
      let version=archiveSchemaVersion(data);
      if(version>CURRENT_SCHEMA_VERSION)throw new Error(`Версия архива ${version} новее поддерживаемой ${CURRENT_SCHEMA_VERSION}`);
      while(version<CURRENT_SCHEMA_VERSION){
        if(version===0){if(!Array.isArray(data.rooms))data.rooms=[];if(!Array.isArray(data.bestiary))data.bestiary=[];if(!Array.isArray(data.tags))data.tags=[];data.schemaVersion=1;version=1;continue}
        throw new Error(`Нет миграции архива v${version} -> v${version+1}`);
      }
      data.schemaVersion=CURRENT_SCHEMA_VERSION;
      return data;
    }
function normalize(data){
  data=migrateArchive(data);
  const normalizeCreature=c=>{if(c.description==null)c.description='';if(c.hp==null)c.hp='';if(c.ac==null)c.ac='';if(c.characteristics==null)c.characteristics='';if(c.abilities==null)c.abilities='';if(c.notes==null)c.notes='';if(!Array.isArray(c.tagIds))c.tagIds=[];return c};
  const normalizeLibraryItem=item=>{if(!item||typeof item!=='object')item={};if(!item.id)item.id=makeId();item.name=String(item.name||'Без названия').slice(0,80);item.description=String(item.description||'').slice(0,240);item.details=String(item.details||'').slice(0,6000);if(!Array.isArray(item.tagIds))item.tagIds=[];item.builtin=Boolean(item.builtin);return item};
  if(!Array.isArray(data.tags))data.tags=[];
  data.tags=data.tags.map(t=>({id:t.id||makeId(),name:String(t.name||'Тег').slice(0,30),color:validTagColor(t.color)}));
  data.bestiary.forEach(normalizeCreature);
  data.rooms.forEach(r=>{if(r.journal==null)r.journal='';if(!r.initiatives||typeof r.initiatives!=='object')r.initiatives={};if(!r.combatNotes||typeof r.combatNotes!=='object')r.combatNotes={};if(!r.currentHp||typeof r.currentHp!=='object')r.currentHp={};if(!r.bonusHp||typeof r.bonusHp!=='object')r.bonusHp={};if(!r.conditions||typeof r.conditions!=='object'||Array.isArray(r.conditions))r.conditions={};if(!Array.isArray(r.entries)){const used=new Set;r.entries=(Array.isArray(r.creatureIds)?r.creatureIds:[]).map(creatureId=>{let id=creatureId;if(used.has(id)){id=makeId();if(Object.prototype.hasOwnProperty.call(r.initiatives,creatureId))r.initiatives[id]=r.initiatives[creatureId];if(Object.prototype.hasOwnProperty.call(r.combatNotes,creatureId))r.combatNotes[id]=r.combatNotes[creatureId];if(Object.prototype.hasOwnProperty.call(r.currentHp,creatureId))r.currentHp[id]=r.currentHp[creatureId];if(Object.prototype.hasOwnProperty.call(r.bonusHp,creatureId))r.bonusHp[id]=r.bonusHp[creatureId]}used.add(id);return{id,creatureId}})}r.entries=r.entries.map(entry=>{const normalized={id:entry.id||makeId(),creatureId:entry.creatureId||null};if(!normalized.creatureId)normalized.npc=normalizeCreature(entry.npc&&typeof entry.npc==='object'?entry.npc:{name:'',description:'',hp:'',ac:'',characteristics:'',abilities:'',notes:'',tagIds:[]});return normalized});const roomEntryIds=new Set(r.entries.map(entry=>entry.id));r.conditions=Object.fromEntries(Object.entries(r.conditions).filter(([entryId])=>roomEntryIds.has(entryId)).map(([entryId,ids])=>[entryId,[...new Set((Array.isArray(ids)?ids:[]).map(id=>String(id||'')).filter(Boolean))]]).filter(([,ids])=>ids.length));delete r.creatureIds;if(!r.combat||typeof r.combat!=='object')r.combat={active:false,round:1,turnCreatureId:null};r.combat.active=Boolean(r.combat.active);r.combat.round=Math.max(1,Math.trunc(Number(r.combat.round)||1));if(r.combat.turnCreatureId==null)r.combat.turnCreatureId=null});
  const hadLibrary=Boolean(data.library&&typeof data.library==='object'&&!Array.isArray(data.library));
  if(!hadLibrary)data.library={syncTags:false,tags:[],conditions:[],conditionPreset:null,conditionPresetSystemVersion:CONDITION_PRESET_SYSTEM_VERSION,artifacts:[]};
  if(typeof data.library.syncTags!=='boolean')data.library.syncTags=false;
  if(!Array.isArray(data.library.tags))data.library.tags=[];
  data.library.tags=data.library.tags.map(t=>({id:t.id||makeId(),name:String(t.name||'Тег').slice(0,30),color:validTagColor(t.color)}));
  if(!Array.isArray(data.library.conditions))data.library.conditions=[];
  data.library.conditions=data.library.conditions.map(normalizeLibraryItem);
  const presetSystemVersion=Math.max(0,Math.trunc(Number(data.library.conditionPresetSystemVersion)||0));
  if(presetSystemVersion<CONDITION_PRESET_SYSTEM_VERSION){
    const selectedPreset=DND_CONDITION_PRESETS[data.library.conditionPreset]?data.library.conditionPreset:null;
    const existingBuiltins=new Map(data.library.conditions.filter(item=>item.builtin).map(item=>[item.id,item]));
    const custom=data.library.conditions.filter(item=>!item.builtin);
    data.library.conditions=selectedPreset
      ?[...DND_CONDITION_PRESETS[selectedPreset].map(item=>normalizeLibraryItem({...item,tagIds:[...(existingBuiltins.get(item.id)?.tagIds||[])]})),...custom]
      :custom;
    data.library.conditionPreset=selectedPreset;
    data.library.conditionPresetSystemVersion=CONDITION_PRESET_SYSTEM_VERSION;
    delete data.library.conditionsVersion;
  }else{
    data.library.conditionPreset=DND_CONDITION_PRESETS[data.library.conditionPreset]?data.library.conditionPreset:null;
    data.library.conditionPresetSystemVersion=presetSystemVersion;
  }
  if(!Array.isArray(data.library.artifacts))data.library.artifacts=[];
  data.library.artifacts=data.library.artifacts.map(normalizeLibraryItem);
  return data
}
